### ISSUE TITLE
Large Group Event Crashing

### ISSUE THREAD

**Issue by mfharding** [twilio/twilio-video.js#1005]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).

For an event of 30 people, users kept on getting disconnected. Users reported getting the error: participant not found error code 53204. 

This was using a modified version of the template app. Can twillio support events up to 50 people with video on?

**Comment by manjeshbhargav** [comment]
Hi @mfharding ,

Thanks for writing in. Since you are subscribing to 30 video tracks, I think your browser is not able to handle rendering all of them. This can result in CPU overload, which will result in being disconnected from the Room because the browser can no longer maintain the connection to Twilio. What is the use case you are trying to implement?

Thanks,

Manjesh Malavalli
JSDK Team
