### ISSUE TITLE
Dynamically set new accessToken

### ISSUE THREAD

**Issue by andersonhail** [twilio/twilio-video.js#1040]
Our customers are regularly on video for > 4 hours, and there is currently a 4 hour limit per participant per room which is due to the max validity of an Access Token being 4 hours. To get around this issue right now we are just having them fully reconnect, but is there a way to pass in a new access token to twilio so that it doesn't need to go through the full Connect lifecycle?

If we were running up on 4 hours, we could fetch a new access token, and then ideally we could just do something like this:

```room.setAccessToken(newToken);```

If there's any other way to achieve this without having to do another ```Video.connect(newToken..)``` that would be great.

Thanks

**Comment by manjeshbhargav** [comment]
@andersonhail ,

Thanks for writing in with your question. Right now, we don't have this in our roadmap. However, what you can do is, when you are close to the 4 hour limit, you can just connect to the Room with a new token and the same identity. We then kick out the existing old Participant from the Room automatically. You don't have to explicitly disconnect the old Participant from the Room.

I'll close this issue since I have answered your question, but we can continue the discussion here. Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team
