### ISSUE TITLE
[Questions] I have a question on details mentioned on the tag release tag 2.1.0!

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1047]
https://github.com/twilio/twilio-video.js/releases/tag/2.1.0

Q1) What necessary action to be take on reconnecting and reconnected events?
Q2) Do we need to detach/attach tracks? 
Q3) Or its just for proper events that provide insightful details for video/audio disappearing of remote participant?
Q4) And whats the difference between registering reconnecting/reconnected event on Room instance and on LocalParticipant instance?

```
room.on('reconnecting', () => {
  reconnecting(localParticipant);
});

room.on('reconnected', () => {
  reconnected(localParticipant);
});
```

```
localParticipant.on('reconnecting', () => {
  reconnecting(localParticipant);
});

localParticipant.on('reconnected', () => {
  reconnected(localParticipant);
});
```

@manjeshbhargav @philnash,

**Comment by manjeshbhargav** [comment]
Hi @kumail-raza ,

> Q1) What necessary action to be take on reconnecting and reconnected events?

This is up to your application use case, but typically you can convey the connection status to the customer through a UI change.

> Q2) Do we need to detach/attach tracks?

Ideally you shouldn't, otherwise the user may think that the RemoteParticipant left the Room.

> Q3) Or its just for proper events that provide insightful details for video/audio disappearing of remote participant?

Yes, attaching/detaching Tracks should only be done if you have subscribed to/unsubscribed from them.

> Q4) And whats the difference between registering reconnecting/reconnected event on Room instance and on LocalParticipant instance?

For the LocalParticipant, there is no difference. However, you can listen to these events even on the RemoteParticipant as shown [here](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#210-february-4-2020).

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team
