### ISSUE TITLE
Pixelated Video Stream from iOS/Safari

### ISSUE THREAD

**Issue by amadoru** [twilio/twilio-video.js#1055]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

When connecting to the rooms from iOS devices, we are most frequently noticing that the video stream that the outbound video stream is pixelated to the receiving party. While this is mostly seen on outbound video from iOS/Safari, we also occasionally notice this on other devices/browsers as well. 

When connecting to rooms we have tested this on Small Group rooms set to gll media region and tested on few regions. We have tested with both VP8 and H.264 video codecs individually. 

Issue is reproducible in both the Twilio video react app as well as on our custom implementation. 

**Expected behavior:**

Video is expected to be of higher quality and is non-pixelated. 

**Software versions:**

 - [x] Browser(s): Outbound: iOS Safari, Inbound: MacOS Chrome/Ubuntu Chrome/etc.
 - [x] Operating System: iOS
 - [x] twilio-video.js: Tested on 2.2.0 & 2.5.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

Note:
This issue may be related to https://github.com/twilio/twilio-video.js/issues/983

**Comment by manjeshbhargav** [comment]
Hi @amadoru ,

Thanks for writing in with your issue. Poor video quality can be due to many things, one of them being packet loss due to poor network conditions. To start off, please provide a couple of Room SIDs where you observed this behavior. Also, it would be great if you can share the ConnectOptions object you are passing to `connect()`.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by amadoru** [comment]
Hi @manjeshbhargav,

Thank you for the response. 

Yes, I understand the perceived quality can be due to many parameters around the network conditions. My objective is to improve the perceived quality of our Twilio Video backed system to have the perceived quality similar to what other major WebRTC based implementations offer (eg: Goog. Meet).

SID: `RM89f6e0fa8174cff3d0ffb94c8a283739`
Codec: `VP8`
Connect Options: `{ audio: true, video: { width: 1280, height: 720, frameRate: 18 }, maxAudioBitrate: 16000, networkQuality: { local:1, remote: 1 } }`

**Comment by manjeshbhargav** [comment]
Hi @amadoru ,

I took a look at our logs for the Room SID you shared, and there seems to have been significant packet loss for the Chrome Participant's video while it is being transmitted to the iOS Participant, most likely due to network issues.

I recommend that you take advantage of a feature in Group Rooms called Bandwidth Profiles, which will properly allocate bandwidth to video tracks based on your network's capacity so that packet loss will be minimized, and therefore pixelation will be reduced. Please use the following ConnectOptions settings: [ConnectOptions for Desktop Browsers](https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#desktop-browser-collaboration-recommended-settings) and [ConnectOptions for mobile browsers](https://www.twilio.com/docs/video/tutorials/developing-high-quality-video-applications#mobile-browser-collaboration-recommended-settings).

Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by amadoru** [comment]
Hi @manjeshbhargav, do you have any update to this? Thanks.

**Comment by manjeshbhargav** [comment]
Hi @amadoru ,

Please add the following to your ConnectOptions:
```js
options.bandwidthProfile.video.mode = 'collaboration';
options.preferredVideoCodecs = [{ codec: 'VP8', simulcast: true }];
```
Our tests and experiences from other customers have shown that VP8 simulcast has better overall video quality. Please try it out and let me know what you find.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by amadoru** [comment]
Hi @manjeshbhargav,

Thank you for the suggestion. We have tested this suggestion and based on our testing, the change of video mode to Collaboration didn't make any visible change for us. Further, the use of code with Simulcast has significantly degraded the video quality, contrary to the expectation of increased quality.

Thanks.

- Roshan

**Comment by manjeshbhargav** [comment]
Hi @amadoru ,

Please send me some Room SIDs which use the new configuration. Also, it would be great if you can send a screenshot of how the mobile client's video looks like from the other client's point of view.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@amadoru ,

I'm closing this issue since I have not heard from you since a long time. Please feel free to re-open if you still need any help in this matter.

Thanks,

Manjesh Malavalli
JSDK Team
