### ISSUE TITLE
Need method of determining whether conversation is connected or not

### ISSUE THREAD

**Issue by treyrich** [twilio/twilio-video.js#11]
In the most recent build of the library the following error has been occurring:
`Cannot transition from "disconnected" to "disconnected"`

This error makes sense to me, but at times it may be convenient to be able to write something along these lines when cleaning things up:
```javascript
if (conversation.isConnected()) {
    conversation.disconnect();
}
```

**Comment by markandrus** [comment]
Hi @treyrich, thanks for the report. We did recently refactor the internals to be more strictly follow state transitions. I think there are two things we could do here

1. Be more lenient in Conversation's `disconnect` method—i.e. is it _really_ useful to throw if `disconnect` is called twice?
2. Expose the Conversation state, either an `isConnected` or some other state property.

**Comment by treyrich** [comment]
Right. I think either would work. I mean honestly I was able to refactor my code to cover most cases pretty well. But it's just nice if in your teardown code you're able to just call `conversation.disconnect()` without having to worry about it potentially throwing an error if it was previously disconnected. It can certainly be handled by the developer, but it seems like since the library is already storing the state that it's redundant for the developer to do so also.

Personally I think that it will promote better, more well thought out, code to go with option 2 and expose the conversation state in some way, and continue the strict checking.

**Comment by markandrus** [comment]
That is good feedback, @treyrich—thank you. I will share it with the team.

**Comment by markandrus** [comment]
Hi @treyrich,

We've recently made a number of changes to the Video SDK: it's now called twilio-video.js instead of twilio-conversations.js; we've also simplified the object model (no more invites, Conversations are replaced by "Rooms", etc.).

The full API docs can be found [here](media.twiliocdn.com/sdk/js/video/v1/docs), but importantly we've

* Added a `state` property to the Room (which is either "connected" or "disconnected"), and
* Multiple `disconnect`s no longer throw.

Hopefully this improves over the Conversations behavior.

Best,
Mark
