### ISSUE TITLE
Desynchronization between additional audio and microphone + camera input on the receiver's end

### ISSUE THREAD

**Issue by Armar2019** [twilio/twilio-video.js#1122]
I'm using twilio-video.js to create a WebRTC video connection between two clients. To the basic camera and microphone tracks, I add an additional sound stream, created from loading a music file and getting a `MediaStream` out of it through Web Audio API. It's then turned into `LocalAudioTrack` and streamed to the other peer.

The problem is, even though everything's working correctly on both sides, the receiving peer experiences slight (but unacceptable for my use-case) desynchronization between the microphone & camera vs additional sound. It's sometimes ahead and sometimes behind the microphone & camera input when compared to what the streaming peer is experiencing.

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

Sadly, I'm not allowed to share the code.

**Expected behavior:**

The receiving peer, even though his connection can lag behind the streaming peer, should be able to receive all tracks as intended by the streaming peer. 

**Actual behavior:**

In addition to normal, but expected connection delays, additional soundtrack is off (either forward or backward) on the receiver's end, when compared to the streamer's intent.

**Software versions:**

 - [x] Browser(s): Chrome & Safari
 - [x] Operating System: Linux & MacOS
 - [x] twilio-video.js: v2.7.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @Armar2019 ,

While camera and microphone are real-time streams, sound coming from a file is not. So, if network conditions are bad, as you are saying, then there is no guarantee of synchronization. One thing you can try is attach all the 3 tracks to the same video element as follows:
```js
const videoEl = document.getElementById('remote-video');
remoteMicrophoneTrack.attach(videoEl);
remoteCameraTrack.attach(videoEl);
remoteSoundTrack.attach(videoEl);
```
This make sure that all 3 tracks are synchronized. But, a disadvantage with this is that if network conditions result in some video packets getting delayed, then video frames might be dropped to keep up with audio tracks. Please try it out and let me know what you think.

I will close this issue since I've answered your question, but we can continue the conversation here.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by beeeemster** [comment]
Hi @manjeshbhargav ,

Is there anything else that you could propose here?

Appreciate your time.
