### ISSUE TITLE
participantDisconnected event stopped working

### ISSUE THREAD

**Issue by nlukovic** [twilio/twilio-video.js#1141]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

### What's going on

Up until a couple of days ago everything was working just fine. Code dealing with Twilio wasn't even looked at. But all of the sudden we stopped receiving events. These two are the issue for now: `participantDisconnected` and `trackSubscribed`(when user publishes a new local audio/video track). I turned on logLevel to debug when connecting and i can see that a user in the room logs that the remoteparticipant's state was changed to `disconnected`(`Transitioned to state: disconnected`). But the `participantDisconnected` event is not firing on the Room object. I have also checked that all users, when they refresh the page or close the tab/window, are calling disconnect method of the room object. Everything else's working just fine except this. Please help 😭

 - [x] Browser(s): Latest chromium based Microsoft Edge, Latest Google Chrome
 - [x] Operating System: macOS 10.15.6
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): React, Redux, Saga...

**Comment by makarandp0** [comment]
Hello @nlukovic, Thank you for writing about this issue. You mentioned that this event was working fine couple of days ago - Were there any changes made to your app since then ? Have you changed the twilio-video sdk version or any other part of your code? Does reverting back to older twilio-video version fix this issue ?   

Thanks,
Makarand

**Comment by nlukovic** [comment]
I found out what was the problem. But the question is how did it work at all before...
The issue was that in other places in code i had a line like this for all remote participants in a `useEffect` cleanup function:
`remoteParticipant.removeAllListeners();`. 
So basically, everything was working just fine with the above mentioned piece of code until it just stopped working.

The reason I even used `remoteParticipant.removeAllListeners();` was that I was getting warnings about too many listeners. Either way, it seems that it now works like it should.

I still wonder why wouldn't I get a `participantDisconnected` event on a `Room` object even though I called `removeAllListeners` on a RemoteParticipant object.

**Comment by makarandp0** [comment]
Glad that you found the issue @nlukovic ! 

`remoteParticipant.removeAllListeners()` would cause `participantDisconnected` to not fire, because `participantDisconnected` is essentially re-emits of the `disconnected` event on RemoteParticipant. Twilio-video internally listens for `disconnected` on RemoteParticipant and re-emits it on the Room object. By calling `remoteParticipant.removeAllListeners()` the internal listener was also removed :)

I will close this issue now.

**Comment by kumail-raza** [comment]
@nlukovic just another user of Twilio and just to know to create more understanding, what scenario makes you to use of removeAllListeners()?
