### ISSUE TITLE
Audio and Video tracks not getting created on Safari/iOS 11+

### ISSUE THREAD

**Issue by Outwitit** [twilio/twilio-video.js#1148]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

When participants join a room, the audio and video feeds get created and can be seen/heard

**Actual behavior:**

When participants join, no audio or video tracks get created

**Software versions:**

 - [x] Browser(s): Safari 11+
 - [x] Operating System: iOS
 - [x] twilio-video.js: 2.7.2
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular

**Comment by makarandp0** [comment]
Hey @Outwitit,  Thank you for writing about your issue.  Can you post some code snippet, and console logs to see if we can spot something. I would also recommend looking at our [Quickstart](https://github.com/twilio/video-quickstart-js) to see if it works in your environment. 

Since you mention angular please not this [common issue](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#angular). 

Thanks,
Makarand

**Comment by Outwitit** [comment]
So I don't have any console outputs! It seems calm. As for snippets I'm not sure what part you'd like to look at.

I'll try the quick start common issued before I write back, thank you for the help!

**Comment by Outwitit** [comment]
Issue was polyfill related thank you!
