### ISSUE TITLE
Pruning?

### ISSUE THREAD

**Issue by jmbldwn** [twilio/twilio-video.js#115]
I could be wrong about this, but it looks like a large portion of the twilio-video js client is polyfills.

I'm building a system that runs on a browser under my control (so I'm using the latest version of Chrome).  Any chance the library can be pruned of the extra code?  I'd be willing to contribute this if others think its useful and someone can suggest a good way to structure and package it.

**Comment by markandrus** [comment]
Hi @jmbldwn, thanks for writing in. Are you talking about the WebRTC polyfills under [`lib/webrtc`](https://github.com/twilio/twilio-video.js/tree/59f98674dcff63e77ed95b05904770d068c73068/lib/webrtc) or something else? The `lib/webrtc` polyfills, based on the numbers below, represent about 13% of the library, in terms of LoC (including comments):

```
$ find lib/webrtc -name \*.js | xargs wc -l
    ...
    1280 total
```

```
$ find lib/webrtc -name \*.js | xargs wc -l
    ...
    9877 total
```

By far, I'd say the biggest contributor to our file size is currently our dependency on SIP.js (which we plan to remove by migrating to plain WS connection, rather than SIP/WS connection). That being said...

> Any chance the library can be pruned of the extra code?

Hmm, I know there are tools like [Rollup](https://github.com/rollup/rollup) that perform [tree shaking](https://github.com/rollup/rollup#tree-shaking); however, that technique prunes unneeded dependencies through static analysis. If you wanted to specifically exclude the Firefox polyfill, this might not be a good technique for that, since the `require` is selected at runtime. I know that certain files can also be excluded from webpack/Browserify by setting a `browser` property in the `package.json`. This might allow ad-hoc exclusion of certain files.

> I'd be willing to contribute this if others think its useful and someone can suggest a good way to structure and package it.

I think step 1 will be to identify the particular files we may want to exclude. Then we can identify some more options for doing so.

**Comment by jmbldwn** [comment]
It's encouraging that you are considering dropping SIP in favor of plain web services.  Knowing this alone makes me more apt to invest in this path. :-) . My main consideration is whether it will get leaner.  Is there a plan for this migration already in place?

**Comment by markandrus** [comment]
> My main consideration is whether it will get leaner.

We definitely want to make the SDK leaner. I'd like to see us sub 100 KB when minified if possible, and I think that will be achievable once we move off SIP.js. We actually proved this out in an internal hack week earlier in the year. Here's a table with numbers from when we did the experiment:

|     | With SIP.js | Without SIP.js | Percent Decrease |
|:--- |:--- |:--- |:--- |
| **twilio-video.js** | 723.388 KB | 294.477 KB | 59% |
| **twilio-video.min.js** | 441.118 KB | 164.639 KB | 63% |

So we have a proof-of-concept and we know we want to do this, but we are still prioritizing with respect to other features we want to launch. Most of the work to support moving away from SIP rests on the backend.

**Comment by manjeshbhargav** [comment]
Hi all, 

We have achieved this milestone since most recent versions of twilio-video.js no longer depend on SIP.js. So, I'm closing this issue.

Thanks,

Manjesh Malavalli
JSDK Team
