### ISSUE TITLE
[Urgent] Participant track = null in RemoteTrackPublication - Safari 12+

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1151]
@manjeshbhargav @markandrus @philnash 

User on Safari not receiving audio/video tracks.

3 Users, RoomSid = **RM30399df737f5f415a23d300c00a28b0f**

- 2 from chrome @ windows (chrome version  84.0.4147.125)
Participant  (sid = **PA43e6abf86f4e9c2877dd1acdb6f2ba18**)
Participant  (sid = **PA75dba93d399dbff0af463a33ea6facbc**)

- 1 from safari @mac (safari version  13.0.4) 
Participant  (sid = **PAb983cabeb032e26fe24ebe8381e1735e**)

![image](https://user-images.githubusercontent.com/2698458/90874612-64557b00-e3b9-11ea-9efd-126bd6b046e4.png)

**Note:** I have tried with explicitly mention only one codec one by one (VP8 or H.264), both has the same results.

**Comment by kumail-raza** [comment]
@philnash @markandrus @manjeshbhargav 

Kindly check this is urgent, I have attached the console.log image.

**Comment by makarandp0** [comment]
Hello @kumail-raza, I looked at the room-sid (RM30399df737f5f415a23d300c00a28b0f) and found that the chrome participants ( PA43e6abf86f4e9c2877dd1acdb6f2ba18 and PA75dba93d399dbff0af463a33ea6facbc ) had  signaling connection error, and was disconnected (and then later reconnected with another participant sid), I wonder if you saw this unsubscribed track because of that?

Does the issue repro consistently - can you provide some repro steps and if possible console logs from the participant that failed to subscribe (track = null).   

thanks,
makarand

**Comment by kumail-raza** [comment]
Yes, @makarandp0 the issue is consistent, and fyi, I have 3 users where 2 users are from chrome @windows, both can see and listen each other, and the 3rd user is from Safari @mac. to be noted chrome users can even receive his tracks, but safari@mac not receiving tracks of chrome users. 

I have tested with chrome @mac, its works fine. I am experiencing issue with Safari@mac. 

Let me know if you need any further details on this or any type of specific logs etc.

**Comment by makarandp0** [comment]
Hey @kumail-raza, I tried this - I used chrome on Mac for 1st two users instead of windows, with 3rd participant on safari on mac. but was not able to repro the issue. Does this repro for you if you use chrome participants from Mac or is it windows specific ? 

Can you share room sid and steps to repro the issue - please include any details on  
a) os versions 
b) browser versions
c) if there is a particular order in which the participant joins/publishes track 

Will ask our QA team once you provide the repro steps.
Thanks,
Makarand

**Comment by kumail-raza** [comment]
Hi @markandrus 

I tried using Twilio QuickStart video application and found its working fine, then on investigate I find that in our product we are creating room on server end where the room videoCodec was explicitly set to H.264, due to which definitely from client and side preferredCodec seems to be not working, I tried change it to VP8 on server end but still no success and experience same issue.

Q) So first of all I need to check whether the room created is having videoCodec with VP8 is there any way? 
Q) Creating a room on server will not work???

**Comment by kumail-raza** [comment]
Attached is the difference between the room created from Quick Start App and Our app.

![image](https://user-images.githubusercontent.com/2698458/92797368-70869400-f3cb-11ea-870f-67179c8b2e1d.png)

**Comment by kumail-raza** [comment]
@makarandp0 @manjeshbhargav @philnash any help!

**Comment by kumail-raza** [comment]
Hey guys!

The solution to my problem is **https://github.com/twilio/twilio-video.js/issues/156**

Thanks!
