### ISSUE TITLE
Video not receiving

### ISSUE THREAD

**Issue by tuanlinh141089** [twilio/twilio-video.js#1154]
Video remote not show on group call

User not receiving video track

Room Sids: RM70b1360875457a056dea09937a7d8625 , RM94ba3024ecc5b0c316e7899921c4a3e5, RM9f0591199ce2d1f807cef95567aadd84

Do not show any error messages on console

1 person can receive and 1 person cannot receive video as shown in the picture

Only 1 user with this error when making a video call will experience this phenomenon

Info Participants:
![image](https://user-images.githubusercontent.com/47776737/91513028-8d23c600-e90d-11ea-8314-fe2e218f6ca1.png)

Software versions:
**Browser**: **Chrome**
**Operating System:** **Window10**
**Third-party libraries**: **Vuejs, twilio-video.js**
Info libraries:
![image](https://user-images.githubusercontent.com/47776737/91514882-1c32dd00-e912-11ea-95a8-889dba433aa7.png)

![bug2](https://user-images.githubusercontent.com/47776737/91436680-c9661080-e892-11ea-81c4-222ac7b30e43.jpg)
![bug](https://user-images.githubusercontent.com/47776737/91436681-c9fea700-e892-11ea-8db0-ab9a192d1ddb.jpg)

**Comment by makarandp0** [comment]
Hello @tuanlinh141089,  Can you provide more details about the issue you are seeing - Any room sids and console logs would be helpful. You can use the template below:


 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**



```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**



TODO

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

**Comment by tuanlinh141089** [comment]
> Hello @tuanlinh141089, Can you provide more details about the issue you are seeing - Any room sids and console logs would be helpful. You can use the template below:
> 
> * [ ]  I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
> * [ ]  I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
> * [ ]  I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
> * [ ]  I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
>   or sensitive account information (API keys, credentials, etc.) when reporting this issue.
> 
> **Code to reproduce the issue:**
> 
> ```js
> // TODO
> ```
> 
> **Expected behavior:**
> 
> TODO
> 
> **Actual behavior:**
> 
> TODO
> 
> **Software versions:**
> 
> * [ ]  Browser(s):
> * [ ]  Operating System:
> * [ ]  twilio-video.js:
> * [ ]  Third-party libraries (e.g., Angular, React, etc.):


I have updated the error information @makarandp0

**Comment by makarandp0** [comment]
@tuanlinh141089 - I do not see any add the information in the template.

**Comment by makarandp0** [comment]
Hello @tuanlinh141089, I am  closing this old issue. Please reopen new issue with the information template.
Thanks,
Makarand
