### ISSUE TITLE
Firefox v79.0 Dimension issues. 

### ISSUE THREAD

**Issue by James91** [twilio/twilio-video.js#1162]
LocalVideoTrack and RemoteVideoTrack video size dimensions incorrect on Firefox compared to Chrome. The following is the code I use to setup the tracks. 

```
connect(this.accessToken, {
        audio: true,
        video: { width: 1280, height: 720 },
        aspectRatio: 1.77777777778,
        logLevel: "debug",
        name: this.videoRoomId
      }).
```

```
createLocalVideoTrack({
   aspectRatio: 1.33333333333,
    video: { width: 640, height: 480 }
})
```

If you see attached the two screenshots, the dimensions are incorrect when performing a call. Is there any idea why this might be? 

I have set the CSS so the image sets into a video container, but the remote video streams is 4.3 instead of 16.9 on firefox.

Thanks for the help. 
![image (5)](https://user-images.githubusercontent.com/1716533/91832252-15bba280-ec3d-11ea-8ea9-07a2d5b52429.png)
![Screenshot 2020-08-28 at 16 49 34](https://user-images.githubusercontent.com/1716533/91831917-94641000-ec3c-11ea-80e3-2dd35124821b.png)

**Comment by manjeshbhargav** [comment]
Hi @James91 ,

I was wondering, why do you have two video tracks? Is it for preview? You can re-use the video track you created in `connect()` in order to display your preview. Regarding the RemoteVideoTrack dimensions being different, that is expected behavior because WebRTC downscales the encoded resolution if the bandwidth is constrained.

Hope this answers your question. Please let me know if you need more clarification.

Thanks,

Manjesh Malavalli
JSDK Team
