### ISSUE TITLE
[Question][Urgent] What was the issue with chrome 85+ with Audio of Programmable Video?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1165]
@makarandp0 @manjeshbhargav @philnash @anna-vasilko @andrewryno 
Just find that and you guys already had a fixed for that, I want to know what actually causing the issue, what was the issue? as I didn't find any such alert from google chrome team. 

https://status.twilio.com/incidents/fvlq6hww7crv

**Comment by kumail-raza** [comment]
@makarandp0 @manjeshbhargav @philnash @anna-vasilko @andrewryno/

hey guys this is urgent! just let me know what the issue was that your team investigated and identified.

**Comment by anna-vasilko** [comment]
Hi @kumail-raza ,

The issue was caused by a bug in our Video Media Server which existed for a long time, but Its occurrence was really low until Chrome 85 started rolling out.
More specifically, the bug was that our Video media server would not forward audio for subscribed tracks in case when they had different extmap ids than the related published track (in RTP Header Extensions). Before Chrome 85 this condition was really rare.  
Google Chrome team confirmed that “Previously libwerbtc/Chrome had a more or less fixed mapping between extension IDs and extension types. Due to implementation changes this is no longer the case and can change based on how/when transceiver objects are created. It's therefore best to not rely on hardcoded mapping of IDs, this is in line with the spec"

The fix in our Video media server side was to no longer rely on fixed mapping of IDs.

We are now working on a public Reason For Outage document. Feel free to share an email with me, so that I can send one to you in a few days. 

We would like to apologize for the impact this incident has had on your users. We are continually working to improve the quality, resilience and robustness of our systems, as our first priority.  We are applying the lessons learned from these events to implement betterments that will prevent failures of this kind from impacting our customers in the future.

**Comment by elebumm** [comment]
Thanks for the great answer @anna-vasilko 👍
