### ISSUE TITLE
[Question][Urgent] twilio-video isSupported return false when I use local ip address to access my local env.

### ISSUE THREAD

**Issue by SFZL** [twilio/twilio-video.js#1169]
We can use localhost and 127.0.0.1 to access twilio quickstart demo, but when we use local ip address to access, the twilio-video.js isSupported return false. I don't know why. Could you please help me.

**Software versions:**

 - Browser(s):  Chrome(85.0.4183.83) and Firefox(80.0.1)
 - Operating System: Windows 10
 - twilio-video.js: 2.7.2

**Comment by makarandp0** [comment]
Thank you for your question @SFZL, 

This is expected behavior. Browsers generally do not allow access to local media and some webrtc apis when a page is loaded using HTTP rather than HTTPS endpoint. It makes exception to this for `localhost` and `127.0.0.1` addresses.

`isSupported` checks for access to those apis, thus returns false for local ip address but true for localhost or `127.0.0.1`

Thanks,
Makarand

**Comment by SFZL** [comment]
It is helpful for me , thanks @makarandp0
