### ISSUE TITLE
Will there ever be an option to toggle if a room is recorded or not mid-session? 

### ISSUE THREAD

**Issue by RusseII** [twilio/twilio-video.js#1178]
With the current version of twilio-video-js, you can specify if a room is recorded or not when you create the room. 

We need functionality for users to be able to record sections of their video meetings (5 minutes out of a 45 minute video call)

Is there, or will there ever be a way to start recording an already created room?

If not, any ideas on how we can add this functionality ourselves with the current system?

**Comment by nattar-netizen** [comment]
Hi there Russell,
This feature is on our roadmap and will be available soon. will you be able to elaborate on the specific use case for the product/company that is seeking this functionality?

**Comment by RusseII** [comment]
Great to hear.

The main use case for it is for video interviews. We work with a lot of staffing agencies - one of the use-cases we are building out is for Send Out interviews. 

In Send Out interviews, a recruiter schedules an interview between their candidate, and the recruiter's client. 

The recruiters + candidate join the interview early to prep right before the interview starts. When the recruiter's client joins the interview room, the recording should start. It should also end as soon as the recruiter's client leaves. 

It is very important that the prep time with the recruiter + candidate is not recorded. 

We also need a way for the recruiter's client to opt out of the recording, and they will be joining while there is already a recruiter and candidate in the room. 

Let me know if further clarification would be helpful.

**Comment by loonpwn** [comment]
Hey @nattar-netizen, we also need this and would appreciate some idea of when we could expect this.

Our use case is that we can only turn on the video recording when all parties in the chat have agreed. So we don't know when the recording would be turned on and we don't want to record without consent (we can't get consent pre-meeting). 

We are getting close to building this functionality and we were planning to have 2 rooms run in parallel and move everyone across when the recording had been agreed on. Ideally, we wouldn't need to build that out because I'm sure we'll run into some problems jumping between rooms.

**Comment by nattar-netizen** [comment]
Hey @loonpwn , I will DM you.

**Comment by papuruth** [comment]
Hey @nattar-netizen, we also need this.
Our use case is that we have two types of video meetings.
1. 1-1 Video Meet
2. Group Video Discussion (50 participants).
We want a recording feature like google meet so that the participant can start the recording manually after joining the room and an indicator to show all the participants that the session is being recorded. Also, a way to retrieve the current recording downloadable media link once the session ends.

**Comment by chrys-exaucet** [comment]
Hello @nattar-netizen,

I am looking forward to getting updates about the availability of the feature. 
My  telehealth company wants allow doctors to record sequences of an online meeting, due to **law requirements**.

**Comment by harlan-zw** [comment]
@nattar-netizen Any update on this?

**Comment by donaltoomey** [comment]
@harlan-zw, have a look here: https://www.twilio.com/changelog/video-recording-rules-api-is-now-generally-available

**Comment by manjeshbhargav** [comment]
We have de-prioritized this feature.
