### ISSUE TITLE
Not able to view peer client's video track

### ISSUE THREAD

**Issue by icodepy** [twilio/twilio-video.js#1188]
Hi All, 

I have started working on Twilio's Programmale Video following the Twilio's Javascript SDK Documentation. 

I have included the code given in the documentation in an Angular Project hosted  using http-server . --ssl. 
I am able to achieve the following using the documentation code: 
1). Creation of a room
2). Two different clients are able to join that room
3). The Clients are able to open the camera and see their own image(s) in the camera
4). generate tokens for the clients from the twilio's testing tool

ISSUES - 1).The clients are able to see their own individual camera image. But they are not able to communicate through the video - one client can't see the face of the other client on the camera UI , video communication is not happening.
2). They can't hear the audio of each other. 

I have followed the exact code given on this link - https://www.twilio.com/docs/video/javascript-getting-started

Kindly provide/suggest a solution. I have been looking for a solution for past 4 days. 

Thank You,
Amir Hasan

**Comment by makarandp0** [comment]
Hello @icodepy, Thank you for writing about this issue.  Have you tried our quick start sample (https://github.com/twilio/video-quickstart-js) - Does that work in your environment? That sample is good way to get started. 

Since you mentioned angular - please note that there are some known issue and workaround needed with some angular versions as noted here: https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#angular

if you still see issues, please share room sid, and client logs from the console. 
Thanks,
Makarand

**Comment by icodepy** [comment]
Hello @makarandp0 , Thank you for your effort to answer my question. 
I have taken help from this [github link](https://github.com/twilio/video-quickstart-js/blob/865fb51e9d363e6c6ee6406c7df28e2582888f9f/quickstart/src/index.js) to solve my current problem.

Thank you,
Amir Hasan
