### ISSUE TITLE
display host, disconnects all remote participants and authentication

### ISSUE THREAD

**Issue by Wajeehkhan123** [twilio/twilio-video.js#1195]
@philnash @markandrus @makarandp0 @manjeshbhargav can we differentiate between the host and other participants, like my scenario is that I want to display the text host for the participant who creates the room and when the host ends or disconnects the meeting, all other remote participants should be disconnected from the room. Moreover, is there any mechanism to authorize and then authenticate the user who wants to join the meeting?

**Comment by philnash** [comment]
With Twilio Video you and your application are responsible for authenticating and authorizing users joining the meeting. It is up to your application whether to provide a user an [access token](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens) to join the room.

As for differentiating between a host and other participants, that can also be up to your application too. One way you could achieve this is by naming the hosts tracks as "host" when you create them, eg:

```javascript
import { createLocalTracks, connect } from "twilio-video";

const tracks = await createLocalTracks({ video: { name: "host" }, audio: { name: "host" });
await connect(token, { tracks });
```

Alternatively, when a host creates a room, you could store the host's identity against the room. Then for your other participants, check the identity of each participant to see who is the host.

As for ending the meeting when the host disconnects, you need to build that as a feature. To do so, when you disconnect your host you also want to [make a request to the REST API to set the status of the room to "completed"](https://www.twilio.com/docs/video/api/rooms-resource#post-instance). That will complete the room and kick out any remaining participants.

Let me know if any of that helps.

**Comment by Wajeehkhan123** [comment]
@philnash you are saying that its up to us that how we authorize and authenticate users for joining the meeting and you are recommending to use the access token to authorize and authenticate the users?
Also, in our scenario, we are only creating the **ad-hoc rooms** i.e. the room creation from client side, so is it possible to update the status of the ad-hoc rooms and storing host's identity against the room using client side?

**Comment by philnash** [comment]
@Wajeehkhan123 The access token only authorizes your user to Twilio Video from the client side. However, your application is responsible for providing your users with the access token, therefore it does the authentication and authorisation.

You can update the status of an ad-hoc room from the REST API, you need to get the room SID from the room in the client side and send it to your server somehow.

When I mentioned storing the host's identity against the room ID, I did mean you'd have to do that in your own datastore somehow. I'm not sure what you're building with, so I can't make further recommendation. There's no function for storing data directly against a room in the Video SDK.

If you are controlling things like this, with a host and with completing rooms, you might consider changing to create your rooms via the REST API rather than ad-hoc. I think it would be more secure and an easier model to deal with than trying to get that information from the client side.
