### ISSUE TITLE
Get Audio/Video tracks of same participant on different devices using same Token

### ISSUE THREAD

**Issue by yogeshpatelfs** [twilio/twilio-video.js#120]
**Requirement**
An iPhone app for video calling using twilio, with feature to [cast to TV using Chrome Cast.](https://stackoverflow.com/questions/44068897/how-to-cast-custom-uiview-to-google-chromecast-ios)

Since Chromecast relies on HTML5/JS for casting, we thought of leveraging the JS library and doing the following:

1.  Create a Twilio video room using IOS APIs from the iPhone App
2. Once the user selects cast, pass the accessToken and the Room name to the HTML5 app (which is displayed on chromecast)
3. Using the accessToken and Room name connect to the Room:
```js
 var connectOptions = {
      name: roomName, 
      audio: false,  // Dont want to use localTrack, since the TV wont have mic
      video: false,  // Dont want to use localTrack, since the TV wont have camera
      logLevel: 'debug'
    };
 Video.connect(accessToken, connectOptions).then(roomJoined, function(error) {
      log('Could not connect to Twilio: ' + error.message);
    });
```
Note: Here we are able to successfully connect to the Room as the iPhone participant. Verified it by matching the `identity` of room.localParticipant with the one attached to the iPhone users token.

4. Use the `room.localParticipant` to get the Audio/Video track and using `container.appendChild(track.attach());` project it on TV

However in step 4. we are not getting the tracks of the iPhone. Is there any way to get the iPhones tracks?

TL,DR: Connect to a Room from DeviceA and try to get the Audio/Video track of DeviceA on DeviceB by connecting to the same Room using the same AccessToken.

**Comment by markandrus** [comment]
Hi @yogeshpatelfs,

Thanks for writing in. So two things:

1. Can you please confirm that you use a unique Access Token for DeviceA and DeviceB? The two Access Tokens should encode the identities of DeviceA and DeviceB, respectively. For example, one Access Token might specify an identity of "device-a" and the other "device-b"; or you could specify "tv" and "iphone"—it's up to you. I'm asking, though, because we enforce uniqueness of identity in the Room. If another Participant connects with the same identity as a previously-connected Participant, we will kick the previous Participant out, and this could cause the Track failures you describe.

2. Can you also ensure you are handling Tracks added via the "trackAdded" event? Can you take a look at our [Usage Example](https://github.com/twilio/twilio-video.js#usage) in the README.md or [my comment in this other, possibly-related ticket](https://github.com/twilio/twilio-video.js/issues/108#issuecomment-299988739)?

Thanks,
Mark

**Comment by markandrus** [comment]
Hi @yogeshpatelfs,

I'm going to close this issue due to inactivity. If you still have questions, please feel free to reopen this issue or open a new issue.

Best,
Mark
