### ISSUE TITLE
Question on Twilio Video and mobile.

### ISSUE THREAD

**Issue by farzaa** [twilio/twilio-video.js#1243]
Hey there! Our product has 6 participants on the call at a time. What we're noticing now consistently is users who join on their iPhones or iPad via Safari on iOS always lag a ton. But, when they switch over to a laptop (same WiFi network as the phone) it all works perfectly and is super smooth.

Does Safari do something like limit the amount of bandwidth it can use or something wacky like that? Just trying to get to the bottom of this :).

**Comment by manjeshbhargav** [comment]
@farzaa ,

Lagging can happen either due to poor network conditions or cpu overload. Next time you see lagging, please check the network quality level (group room only) and see if it is low. I'll close the issue since I answered your question, but we can continue the discussion here.

Thanks,

Manjesh
