### ISSUE TITLE
Unexpected state "closed" for handling a "heartbeat" message from the TCMP server

### ISSUE THREAD

**Issue by FredCoen** [twilio/twilio-video.js#1254]
Joining room works but participants joining doesn't seem to work. From the code below the first log prints as expected when joining a room. However, the second log which is supposed to print when someone else joins the room doesn't print. Instead the warning  "Unexpected state "closed" for handling a "heartbeat" message from the TCMP server " prints. Followed the twilio documentation one for one.. Someone having this issue?

**Code to reproduce the issue:**
```
const room = await connect(token, { name:'room1', audio: true, video: { width: 640 } })
console.log(`Successfully joined a Room: ${room}`); 
room.on('participantConnected', participant => {
        console.log(`A remote Participant connected: ${participant}`);  
}       
```

**Software versions:**

 - [ ] Browser(s): Chrome
 - [ ] Operating System: Mac
 - [ ] twilio-video.js: ^2.7.2

**Comment by manjeshbhargav** [comment]
Hi @FredCoen ,

It looks like you are getting disconnected when the second Participant joins. It is most likely because you are using the same identity string to create tokens for both Participants. Please use unique identity strings for different Participants. Hope this fixes your issue.

I'll close the issue, but please feel free to reopen if you still see the problem.

Thanks,

Manjesh
