### ISSUE TITLE
[General Question] What does Network Quality API actually measure?

### ISSUE THREAD

**Issue by adilanchian** [twilio/twilio-video.js#1255]
Hey Twilio Team 👋!

First off, thanks for the awesome service here. Makes understanding video/audio tech pretty great! 

I was looking for some quick clarity on the Network Quality API. From what I have read in the docs and information I gathered this is my understanding:

1. I am in a room with 3 other participants (4 in total)
2. I have enabled the listeners to collect local and remote network diagnostics
3. I have setup a simple UI that shows the quality (0 - 5) for each participant
4. For my local track - the measurement I am seeing is my quality connection to the Twilio Servers
5. For all remote tracks - the measurement I am seeing is the quality of their connection to the Twilio Servers

Is my understanding correct here or am I missing something here? Appreciate your time in advance!

**Comment by manjeshbhargav** [comment]
Hi @adilanchian ,

You are correct. The network quality level describes whether the client has enough bandwidth to send and receive media that it is publishing and subscribing. 5 implies the client has sufficient bandwidth and 1/0 means not enough bandwidth. So, you can have a situation where if you are not publishing or subscribing to media, your score will always be 5 since there is enough bandwidth for no media.

Hope this clarifies things.

Thanks,

Manjesh

**Comment by farzaa** [comment]
Ty for this answer!!!
