### ISSUE TITLE
Not getting Preview of All participants entered later in a room

### ISSUE THREAD

**Issue by Muzaffar-Munir** [twilio/twilio-video.js#1295]
- [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
// TODO
```

**Expected behavior:**

Every Participant can see All participants who have joined that room

**Actual behavior:**
Hi! I am implementing Twilio Video using Vuejs and I have a problem in Vue js in which the **initiator(first participant)** is getting a preview of all participants but the other participant is getting a preview of only participants entered later in a room. e.g "AA" is the **first Participant** and "BB" is the **second participant** and "CC" is **third Participant**. Now "AA" getting a preview of "BB" and "CC" but "BB" is only getting a preview of "CC" and "CC" is just getting his preview. I don't know where I mess up things

**Software versions:**

 - [ ] Browser(s): Chrome
 - [ ] Operating System: Window 10
 - [ ] twilio-video.js:
 - [ ] Third-party libraries: Vue js

**Comment by makarandp0** [comment]
Hello @Muzaffar-Munir, Thank you for writing about this issue.

Can you post your code - so that we can see if we can find something. But looking at the symptoms, I suspect you are only relying on `participantConnected` event to handle participants as they connect but are not handling the "existing" participants when a somebody joins the room.

Please see [this code](https://github.com/twilio/video-quickstart-js/blob/master/quickstart/src/joinroom.js#L234), and ensure that your code has similar handling.

Thanks,
Makarand

**Comment by Muzaffar-Munir** [comment]
@makarandp0 thanks for your help, i have solve the issue, as you said earlier i was doing the same mistake, thanks again for your help
