### ISSUE TITLE
Raise and error/Output Debug info if no dialog exists while inviting a participant.

### ISSUE THREAD

**Issue by VinayNadig** [twilio/twilio-video.js#13]
Steps to Replicate:

1. Create a Conversation Client.
2. Invite a new Participant. (A new conversation gets created at this point)
3. Disconnect the new Participant. (Network down/Tab closed etc)
4. Invite a participant with the same conversation object. (Number of participants is now 0 and 0 dialogs exist).

The above steps fail silently without any debug info/error.

Relevant code:

https://github.com/twilio/twilio-conversations.js/blob/32c8ceabfa34c97da2c6ce3a74a6d3f44a22145f/lib/signaling/v1/conversation.js#L360

**Comment by markandrus** [comment]
Thanks for the report, and thanks for including steps to replicate, @VinayNadig. This is something we plan on addressing.

**Comment by markandrus** [comment]
Hi @VinayNadig,

We've recently made a number of changes to the Video SDK: it's now called twilio-video.js instead of twilio-conversations.js; we've also simplified the object model (no more invites, Conversations are replaced by "Rooms", etc.).

Importantly, we've completely refactored the signaling internals, so these sorts of Dialog issues should no longer occur.

Best,
Mark
