### ISSUE TITLE
[Question] How to test Simulcast?

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#1329]
I have few quick questions, as we have enabled simulcast recently https://www.twilio.com/docs/video/tutorials/working-with-vp8-simulcast#enabling-simulcast-chrome, 

Q) Our QA engineer like to test it can you please provide any guide on it?
Q) How can I check using REST api that Simulcast option is enabled?

**Comment by kumail-raza** [comment]
@manjeshbhargav @philnash ?

**Comment by makarandp0** [comment]
Hi @kumail-raza, Thank you for your question. 

You can verify if simulcast is enabled and working correctly by checking stats on client side. 

On sender side - the one who is publishing video with simulcast enabled) - `room.getStats` api would  show track stats with multiple layers (with different resolutions) being sent. 

For example `(await room.getStats())[0].localVideoTrackStats` should evaluate to something like this: 
 
![Screen Shot 2020-12-29 at 5 33 53 PM](https://user-images.githubusercontent.com/6174737/103324397-47325800-49fc-11eb-8dbb-2f24cbe893c2.png)

Notice that three layers for the same track are being sent. When simulcast is not enabled you would see just single layer being sent.

Now you can check the stats from the receiver side and ensure that a lower resolution layer gets sent for the receiver with lower available bandwidth, where as higher resolution layer gets sent to participants with higher bandwidth availability.  
![remote Video Stats](https://user-images.githubusercontent.com/6174737/103324716-87460a80-49fd-11eb-8475-9ec455795f49.png)

In the image above we see that the track layer with 1280x720 was received. 

Let me know if that helps,
Thanks,
Makarand

**Comment by kumail-raza** [comment]
Great! Thanks!

**Comment by kumail-raza** [comment]
@markandrus I just in the logs that all the three video tracks have the same dimensions (width/height), can you tell me what I doing wrong or what could be the issue?

![image](https://user-images.githubusercontent.com/2698458/103340824-eb70d900-4aa6-11eb-8927-f43afe52d17b.png)

**Following are the options that are passing into `Twilio.Video.connect()`**

![image](https://user-images.githubusercontent.com/2698458/103340970-50c4ca00-4aa7-11eb-879e-a85bf9d82e4e.png)

**Comment by makarandp0** [comment]
That sounds odd  -  Since you are capturing at 640x480, we should see two layers 640x480 and 320x240.
Looks like you are passing tracks array - does it contain video track as well? Can you confirm that the published track `[...room.localParticipant.videoTracks.values()][0].track.dimensions` is the dimension you expect ? 

Also try capturing at `1024x768` and see if you still see similar layers.

**Comment by kumail-raza** [comment]
@makarandp0 
Here are the details of the Array in tracks:
![image](https://user-images.githubusercontent.com/2698458/103399019-f7b96c80-4b60-11eb-92b3-06e9857992b3.png)

**Comment by kumail-raza** [comment]
@makarandp0 on capturing at 1024x768 following is the result, 2 tracks dimensions are same where one is different which seems wrong to me! 

![image](https://user-images.githubusercontent.com/2698458/103399665-e9208480-4b63-11eb-9237-f4ceed367f83.png)

**Comment by makarandp0** [comment]
Hello @kumail-raza, 
`connectOptions` members `tracks` and `video` are mutually exclusive. since you are passing `tracks` array your `video` parameter is getting ignored. How do you acquire track that you pass in `tracks` array - what constraints are used to acquire it? Can you confirm `[...room.localParticipant.videoTracks.values()][0].track.dimensions` shows the values you expect?

**Comment by kumail-raza** [comment]
@makarandp0 

> **connectOptions** members tracks and video are mutually exclusive. since you are passing tracks array your video parameter is getting ignored.

In the app the tracks are creating using `Twilio.Video.createLocalTracks()`. You are saying I should not pass generated tracks with this function?

> How do you acquire track that you pass in tracks array - what constraints are used to acquire it?

By passing this options {video : {width: 640, frameRate: 24, height: 480};}

> Can you confirm [...room.localParticipant.videoTracks.values()][0].track.dimensions shows the values you expect?

Is not about what dimension local participant get, actually QA need to verify if simulcast is enabled properly or not, for that I am getting details from `.getStats()`

**Comment by makarandp0** [comment]
Hello @kumail-raza,

passing generated tracks to Video.connect is as `connectOptions.tracks` is fine, but in that case you can remove `connectOptions.audio`, `connectOptions.video`  parameters, as they have no effect. 

For checking the simulcast layers that are getting sent, using `.getStats` is a good idea. I asked for `[...room.localParticipant.videoTracks.values()][0].track.dimensions` just to confirm the dimensions for published track, because this dimension determines the layers of simulcast  that get sent as listed [here](https://www.twilio.com/docs/video/tutorials/working-with-vp8-simulcast#resolution-and-layers)

**Comment by manjeshbhargav** [comment]
Hi @kumail-raza ,

I'm closing this issue since @makarandp0 has answered all your questions. However, please feel free to continue the conversation here if required.
