### ISSUE TITLE
[Question ] Is Chrome on iOS officialy supported

### ISSUE THREAD

**Issue by wandroll** [twilio/twilio-video.js#1345]
WebRTC in iOS 14.3 iframe/WKWebView is now allowed. Hence it seems possible now to have a video through Chrome on iOS.
We tried and found only one smallish bug related to reconnection when reloading page where room participants list was empty.

My question is : is Chrome iOS offically supported ( or when will it be ) ?

**Comment by manjeshbhargav** [comment]
Hi @wandroll ,

Thanks for writing in with your question. We are not officially supporting Chrome on iOS yet. However, it is something we want to work on soon. However, you are free to use the SDK in Chrome iOS, although we won't be in a position to provide support for it yet. I will close this issue for now. However, can you describe the reconnection issue so that we can make a note of it internally?
