### ISSUE TITLE
Black video on chrome v88 windows and os

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1363]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitxHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**

Participants can see video of participant.

**Actual behavior:**
Participants can see only black video. In local stream participant can see himself.
Happened for participants on windows and mac on chrome v88. On Firefox it works
![image](https://user-images.githubusercontent.com/10713004/106250854-79f68880-6214-11eb-8bed-fcfb0b436db0.png)
![image](https://user-images.githubusercontent.com/10713004/106261787-5afef300-6222-11eb-9482-92abe76f37e2.png)

**Software versions:**

 - [x] Browser(s): Chrome v88
 - [x] Operating System: OS
 - [x] twilio-video.js: v2.10.

**Comment by dreamerchandra** [comment]
Also observed on MacOS 11.0.1 
`trackSubscribed` event didn't come
twilio-version: 2.7.2

**Comment by rpdobson123** [comment]
We have one internal user encountering this exact problem somewhat regularly. Local track is visible but remote track is black screen.

They're in a different timezone / geographically farther than the rest of the team, maybe network related? They're using Chrome on Catalina (macbook).

**Comment by manjeshbhargav** [comment]
@CyranMS ,

Thanks for writing in with your issue. Can you share some Room SIDs to start off? Also, it would be great if you can share your JavaScript console logs by setting `logLevel: 'debug'` in ConnectOptions?

Thanks,

Manjesh

**Comment by vincentfretin** [comment]
Probably an issue in Chrome 88, see https://bugs.chromium.org/p/chromium/issues/detail?id=1168948
https://groups.google.com/g/meetecho-janus/c/OMzqEDDatew/m/zga9fM_jAAAJ

**Comment by CyranMS** [comment]
Room SID: RM45469f7064c057e82fe7001617d6a19c
 @manjeshbhargav

**Comment by manjeshbhargav** [comment]
Hi @CyranMS ,

I took a look at our logs, and looks like the Chrome 88 Participant did not send any video bytes to the RemoteParticipants. I also saw that you are using H264. I have two comments:

1. As @vincentfretin suggested above, it might be due to the Chromium issue regarding the H264 encoder fails silently when hardware acceleration is disabled. Can you run your test with hardware acceleration enabled to see if it fixes the issue?
2. Any particular reason you're using H264 and not VP8. From our testing, we have observed that VP8 generally performs better in terms of quality and bad network conditions. Also, you can take advantage of VP8 simulcast with out bandwidth profile APIs in order to handle different Participants with different network conditions.

Thanks,

Manjesh

**Comment by CyranMS** [comment]
Hi Manjesh,
Thanks!
1. That participant also tried it on Google meet. Same result. So the codec is probably not the issue. 
2. We will look into it. So should we just go for the setting vp8 & h.264 for our rooms?

**Comment by swarnava** [comment]
Chrome has released new build 88.0.4324.146 which should fix the issue!

**Comment by kirillkorneevcb** [comment]
I can confirm that the issue is not present in 88.0.4324.150 but it looks like it has come back in Chrome Beta 89.0.4389.40 and Chrome Canary 90.0.4408.0
I have tried our own implementation and the Twilio's own quickstart

**Comment by kunaljham** [comment]
Hi there --

We're experiencing the same issue after updating to Chrome version 89.0.4389.72 on Mac. Note that this issue was non-existent on Chrome version 87 and below.

Twilio Video JS SDK version 2.3
Twilio Video iOS SDK version 3.7.2
P2P rooms only

Here's what we have found so far:
- calls between iOS and chrome on desktop do not work. The video feed does not seem to be published on either end as we are seeing a blank screen for the remote feed on both ends
- calls between two web clients on chrome work
- calls between iOS and Firefox on desktop work, calls between iOS and safari work

**This is becoming a pretty big issue for us as our users upgrade to the latest version of chrome.**

**Comment by kirillkorneevcb** [comment]
> Hi there --
> 
> 
> 
> We're experiencing the same issue after updating to Chrome version 89.0.4389.72 on Mac. Note that this issue was non-existent on Chrome version 87 and below.
> 
> 
> 
> Twilio Video JS SDK version 2.3
> 
> Twilio Video iOS SDK version 3.7.2
> 
> P2P rooms only
> 
> 
> 
> Here's what we have found so far:
> 
> - calls between iOS and chrome on desktop do not work. The video feed does not seem to be published on either end as we are seeing a blank screen for the remote feed on both ends
> 
> - calls between two web clients on chrome work
> 
> - calls between iOS and Firefox on desktop work, calls between iOS and safari work
> 
> 
> 
> **This is becoming a pretty big issue for us as our users upgrade to the latest version of chrome.**
> 
> 

Updating iOS SDK to the latest 4.3 version solved the problem for me.

**Comment by amenon** [comment]
We just started seeing `signaling_connection_timed_out` errors for users on Chrome 89 on a Mac video chatting with iOS users. Here is a room SID where we tested a participant on Chrome 89 video chatting with a participant on iOS: RM13ac2fb68ffdc92090abb786ad6e2db1

We are running  twilio-js 2.13.0 on the web and are only having video call connection issues on Chrome 89. Everything works normally on Chrome 88 and Safari 14.

**Comment by makarandp0** [comment]
Hello @amenon - Thank you for reporting this. I suspect that you are running into an interop issue between Chrome 89 and older versions of mobile SDKS that we just found about and are actively investigating (VIDEO-4329). We will keep you posted on our progress and findings. (VIDEO-4329)

In the meanwhile if you are willing to try some workaround in your browser app, I would like to validate a theory that we have. Please send me an email and we can try it out.

Thanks,
Makarand

**Comment by makarandp0** [comment]
Hello  @amenon, @kunaljham  @kirillkorneevcb,  We have created a separate issue for the interop with chrome 89, Please follow https://github.com/twilio/twilio-video.js/issues/1409 for updates on it.

**Comment by makarandp0** [comment]
Closing this old issue as chrome 89 issue is already resolved. Please reopen a new issue if you still see this problem.
