### ISSUE TITLE
[P2P][Chrome 89][iOS 3.x][Android 5.x] Mobile Participants cannot see or hear Chrome Participants.

### ISSUE THREAD

**Issue by manjeshbhargav** [twilio/twilio-video.js#1409]
## Description

In a Peer-to-Peer Room, mobile participants that are using [these versions](#affected-sdks) of the Twilio Video SDKs cannot see or hear Chrome 89+ Participants.

## Root Cause

Chrome 89 is [deprecating](https://groups.google.com/g/discuss-webrtc/c/Zrsn2hi8FV0/m/KIbn0EZPBQAJ) Plan-B SDPs, and a result, it is adding the `a=extmap-allow-mixed` line in its SDPs by default. However, these SDPs are not interoperable with WebRTC versions 70 or lower. Because of this the above-mentioned mobile Participants fail to establish media connections with Chrome 89+ Participants.

<h2 id="affected-sdks">Affected SDKs</h2>

* [JS] 2.x or lower on Chrome 89+
* [iOS] 3.x or lower
* [Android] 5.x or lower

## Solution

**UPDATE:** The issue has been fixed server-side and is fully rolled out. No client side workaround needed. See details in this comment [here](https://github.com/twilio/twilio-video.js/issues/1409#issuecomment-791844635).

**OLD**
The solution is to remove `a=extmap-allow-mixed` from Chrome 89+ SDPs. We are working to update our back end with this solution. In the meantime, you can temporarily work around this issue by passing `offerExtmapAllowMixed: false` in ConnectOptions in your JavaScript app:

```js
const { connect } = require('twilio-video');

const room = await connect('$TOKEN', {
  offerExtmapAllowMixed: false
});
```

*Please watch this space for updates regarding the back end fix for this issue.*

**Comment by gjdownes** [comment]
@manjeshbhargav are there any side-effects to setting `offerExtmapAllowMixed` to false for Chrome versions below 89?

Also, does this workaround also apply to 1.x JS versions?

**Comment by kunaljham** [comment]
In my testing, it looks like the video calling works with `offerExtmapAllowMixed=false` on Chrome 80.0.3987.149 as well. I downloaded a random older version of Chrome from https://www.slimjet.com/chrome/google-chrome-old-version.php. From the description in the [release notes](https://groups.google.com/g/discuss-webrtc/c/Zrsn2hi8FV0/m/KIbn0EZPBQAJ) for Chrome 89, it sounds like it should work for Chrome 71 onwards.

**Comment by anna-vasilko** [comment]
Update
The server-side fix is now fully rolled out. Your newly created rooms will no longer be impacted by the issue. You do not need to use the workaround anymore since the fix removes the SDP line which was causing the issue in peer to peer rooms between Chrome 89 and some of the mobile clients. 

We would like to apologize for the impact of this issue. Our automated tests detected the issue when Chrome 89 started rolling out to the stable channel. We will work on improvement to detect such issues earlier in the browsers release lifecycle, as soon as new browser versions get released to beta/dev channels. 

Best regards, Anna Vasilko

**Comment by ramapal** [comment]
Closing the issue since it has been resolved.
