### ISSUE TITLE
Change mediaStreamTrack in existing AudioTrack

### ISSUE THREAD

**Issue by szwowo** [twilio/twilio-video.js#1457]
Hi,
I am wondering if there is an option to change mediaStreamTrack in existing AudioTrack without calling publishTrack on localParticipant. 

I have an app with videocall and I want to stream audio from different files, but when I am doing this via publishTrack method there is a few seconds delay in the interlocutor side.

**Comment by manjeshbhargav** [comment]
Hi @szwowo ,

We have a `restart()` method on the `LocalAudioTrack`. However, this applies only to microphone tracks and not to tracks playing files. However, there is a private method called `_setMediaStreamTrack(mediaStreamTrack)`, which you are free to try out, but since it is a private method, use it at your own risk.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team
