### ISSUE TITLE
Losing audio when unplugging earphones

### ISSUE THREAD

**Issue by gritbranch** [twilio/twilio-video.js#1516]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

`video-quickstart-js`

Hi,

I am experiencing an audio issue when running video-quickstart-js. I start the call with my earphones plugged in. When I unplug my earphones, the participant from the other end loses my audio and won't hear me. Plugging the earphones back in will not recover the audio. The only time the other participant can hear me again is when I leave the room and rejoin the call.

**Expected behavior:**

Remote participant should still be able to hear me when I unplug my earphones.

**Actual behavior:**

Remote participant loses my audio completely.

**Software versions:**

- [x] twilio-video.js: 2.15.1

This issue is fairly consistent and reproducible on the machine-browser combination listed below:

Local Participant's Machine
Mac M1 (11.4)
Safari: 14.1.1
Firefox: 89.0.2
Chrome: 91.0.4472.114

Remote Participant's Machine
Windows:
Chrome: 91.0.4472.124

Mac (10.14.6)
Chrome: 91.0.4472.114

**Comment by PikaJoyce** [comment]
Hey @gritbranch!

Thanks for opening up this issue and I apologize for the delayed response. But I believe that the Quickstart Application does not include the logic to be able to hand off audio input/output switch off. However, we do have an example that does include this sort of logic. Please take a look at the media device selection example [here](https://github.com/twilio/video-quickstart-js/tree/master/examples/mediadevices) to see if you're still experiencing that same issue. 

Best,
Joyce

**Comment by gritbranch** [comment]
Hi @PikaJoyce,

Thanks for the reply. I failed to mention in my previous post that I'm using a 3.5mm headphone jack. Anyway, I have tried the link you sent me for both Mac and Windows. Yes, plugging and unplugging the headphone jack works, but they behave rather differently. For example, for my Mac, when I plug the headphone jack, this piece of code will fire:

In the file: `examples/mediadevices/src/index.js`

```
// Whenever a media device is added or removed, update the list.
navigator.mediaDevices.ondevicechange = updateDeviceSelectionOptions;

```
What will happen is I will have an extra media device when plugging my earphones which I have to select in the Audio Input dropdown and click 'Apply' for it to work. For Windows, I didn't have to do this to recover audio.

Cheers.

Ryan

**Comment by PikaJoyce** [comment]
Hey @gritbranch,

This makes sense as they are different devices and I believe that how the device/OS handles default audio input/output will differ. 

However, I've been unable to reproduce this as I'm able to swap between default devices on my macbook pro (from my speakers, to my headphones, to airpods) without having to apply the changes manually. We noticed that you're also on a Mac M1, I was wondering if you could try this out on a non M1 mac to see if the problem still occurs?

Additionally, please take a look at this [demo app](https://makarandp0.github.io/twilio-video-api/). You won't be able to connect to a room, but this application should be able to provide more details on what might be happening. Since this is happening on your LocalParticipant track, please add `Local Audio` and connect/disconnect as you did in the quickstart. Hopefully this will uncover some more details as to why this may be happening.

Thank you,
Joyce

**Comment by gritbranch** [comment]
Thank you, @PikaJoyce , 

I will close this issue as this appears to be OS related rather than Twilio. But FYI,  I tested this issue on 2 non-M1 Macs, and the result is different:

OS 10.14.6 -  earphones automatically switches (i.e. ondevicechange doesn't fire).
OS 11.3.1 - earphones have to be switched manually as it produces a completely separate media device (i.e. ondevicechange fires).

Thanks again for your help on this.

Cheers.

Ryan
