### ISSUE TITLE
Connecting to a room only as a listener?

### ISSUE THREAD

**Issue by nikolalukovic** [twilio/twilio-video.js#1653]
I've been using twilio for the last 2.5 years and it works very well. I know that before I wasn't able to connect to a group room without providing a local audio track from microphone. Is that possible now or is it a planned feature maybe? To be able to connect to a group room without microphone and camera to just be a listener?
Thanks!

**Comment by charliesantos** [comment]
@nikolalukovic yes this is now possible. You can provide an empty `tracks` array in your `ConnectOptions` to achieve it.
On a related note, have you seen [Twilio Live](https://www.twilio.com/live)? It might be good for your use case.

**Comment by charliesantos** [comment]
@nikolalukovic you will still use programmable video to connect your speakers to a room. The difference is, you can use Twilio Live to stream your room and have your "listener-only participants" to connect to that stream. The difference is, you can support millions of listeners and viewers. Please checkout [Twilio Live](https://www.twilio.com/live)'s homepage for more details.

I'm closing this ticket now since the original question has already been answered. But as always, please feel free to follow up :)
