### ISSUE TITLE
A lot of participants with TwilioError 53000 error 

### ISSUE THREAD

**Issue by CyranMS** [twilio/twilio-video.js#1730]
Hi,
every day we have around 2-5 participants per day that cannot connect to Twilio due to 53000 errors. 
> [TWILIO] WRN error Error: Signaling connection error 53000: 53000

Is there anything we can do for these cases? 
Is it expected that so many people are affected? 
What are the reasons for this? 
What do you recommend to do to still enable a meeting? 
[This article](https://www.twilio.com/docs/api/errors/53000) recommends trying another region. Why would that help?

Cases:
- RM8274cb6fb9f080788d8fb77ec81d7385
- RM70828a079be19b870ab30fd1eeeaa81d
- RM512ff437c4396b1aa8e5c391c8c8ba27
- RM180c4b6684f1f83d35dac6eca9da374a
- RMd4aa51f5dd713bfa366b9aed796dafd4

(and many more - let me know if you need me to provide them)

**Comment by PikaJoyce** [comment]
Hi @CyranMS 

Thanks for opening this issue and providing some room sids. It's difficult to provide a concrete answer here. I've taken a look at those logs based on the room sids but I don't immediately see anything glaringly wrong. 

Would it be possible for you to provide more details such as device and OS used?
Is this reproducible on our [quick start application](https://github.com/twilio/video-quickstart-js)?

Thanks,
Joyce

**Comment by CyranMS** [comment]
Thanks, @PikaJoyce - is there no way for you to see the OS and device in the logs? 
Here is some data for you. Does that help?
<img width="807" alt="image" src="https://user-images.githubusercontent.com/10713004/157675636-6f4b5374-2076-4ce3-b2c0-58783b570788.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/10713004/157675682-710c0ed9-b23a-4807-9b0b-34fada139512.png">
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/10713004/157675764-78ee94d9-df3f-49e7-8158-718df21286d1.png">

**Comment by PikaJoyce** [comment]
Hi @CyranMS,

Apologies for the delayed response. I've taken a look at those room sids and I don't immediately see anything totally out of place. There's a couple of rooms with only one participant in them (unsure if this was intentional) or if there was meant to be more and they were never able to connect? And double checking to make sure that their network is stable? 

I'd love to dig a bit deeper though. Would it be possible for you to provide some client side logs as well? It'd greatly help in our investigations! 

Thank you,
Joyce

**Comment by CyranMS** [comment]
Yes, the ones where there is only one person. The other participants were not able to join.

**Comment by CyranMS** [comment]
More cases

RM6e311434bc84399cfd76a4366b91f8f1
Room: RM4e39d1d668fabf41d428e3aa3dbe3cc7
- Browser: Chrome 98.0.4758
- OS: Windows 10

**Comment by anna-vasilko** [comment]
Hi @CyranMS 
Thanks for the fresh room sids. We are bringing more eyes to investigate the issue. 

Normally those signaling errors mean that end user's network is not stable enough to establish a signaling connection. So we recommend customers to implement a pre-call checks in their applications for users to validate the network is good enough for a video call and recommend switching to different network otherwise etc. We have built an API and a demo app for this purpose. You can read on[ in this blogpost](https://www.twilio.com/blog/video-diagnostics-app-reactjs-preflight-api).

Meantime we will dig more into the logs to see if there is something special happening in your case.
If you want to talk to Twilio Video product manager, please request it via your twilio account manager or create a support ticket via Twilio Console (and share its number here) so we can arrange for a call in there.

**Comment by ykhodosh** [comment]
Hi @CyranMS, I'm looking into our backend infra to see, if we can identify the issue, and I have a question for you. I noticed that you have clients connecting from Americas as well as Europe. Is this issue specific to a particular region/continent or it happens everywhere?

**Comment by CyranMS** [comment]
@ykhodosh Thanks! In the last 90d, we see it happening for 151 participants in Germany, France 26, and UK 12. In the US it happened only 8 times (all based on sentry). It is odd that our websockets and also websockets by sendbird work fine but they cannot connect to twilio. 
 
 @charliesantos we will get back to you on that one

**Comment by cengit** [comment]
i see the same issue, in my case the root cause is: **our intranet can NOT connect to twilio server**, so please make sure your network can connect to External network

**Comment by michalzaq12** [comment]
Any updates?

**Comment by michalzaq12** [comment]
I would like to share my observations regarding this error.

`Error: Twilio 53000 - Signaling connection error`
Just before the error occurred: `warn [TwilioConnection #1: wss://global.vss.twilio.com/signaling] Closed: 1006 - `

Close Code 1006 is a special code that means the connection was closed abnormally
Usually this is caused by WebSocket-incompatible proxies, which can't close the connection in the correct way.
or End-user devices tend to lose network connectivity often and unpredictably


**SOLUTION**: Twilio-video js SDK should retry the WebSocket connection (same as when receiving a message about the server busy) after receiving 1006 WebSocket error code
https://github.com/twilio/twilio-video.js/blob/0029114f2609b097023cdf1555adefd5c8aeffe4/lib/twilioconnection.js#L360


Useful links:
https://community.cloudflare.com/t/websocket-failing-randomly-with-error-code-1006/388361
https://websockets.readthedocs.io/en/8.1/faq.html#what-does-connectionclosederror-code-1006-mean
https://support.pusher.com/hc/en-us/articles/4412491141265-What-Is-Meant-By-Channels-Error-1006-

cc @ykhodosh @PikaJoyce

**Comment by CyranMS** [comment]
Yes @michalzaq12 
We have not found a good solution for now. We wonder if the reason is that the signaling server is in the US with an AWS IP address and that some companies block it deliberately. 

Also even if they can connect they sometimes disconnect as you pointed out. I wonder if a signaling server in Europe would help here.

**Comment by michalzaq12** [comment]
FYI: I use Ably for notifications in real time (also over websocket) and there is no such error (1006)
