### ISSUE TITLE
Stopping cloned remote MediaStreamTrack will stop audio in the original MediaStreamTrack.

### ISSUE THREAD

**Issue by gicuuu3** [twilio/twilio-video.js#1811]
Hello! I'm reporting a bug here that seems to be caused by latest chromium but providing the same info here in case you'd be able to help with potential workarounds or more data collection

---

Chrome Version       : 103.0.5060.53 (Official Build) (64-bit) 
Twilio Version           : 2.21.1
OS version               : All of them

Behavior in Safari (if known): Works without issue
Behavior in Firefox (if known): Works without issue

---
### What steps will reproduce the problem? (unsure yet since have not create a pure simple reproducible env. reproduced on our product)

(1) Have more than 3 html video elements with audio tracks attached with display 'none' + Have some video elements visible on screen (we currently split audio and video streams into their individual playback elments)
(2) Modify UI so that the previously visible video track playback elements are removed leaving only the backgroud audio track ones.
(3) MediaStreamTrack<audio> associated to the hidden video elements will become silent and can only be "fixed" by setting the `enabled` property from true => false => true again

---
### What is the expected result?

Audio track playback does not get interrupted

---
### What is the actual result?

Audio track playback does get interrupted

---
### Any additional information (anything else which may help us debug the issue)?

Not yet since I'm writing this the moment I realized the bug is reproducible on our system. My guess is it might be some newly implemented autoplay rule that misfires? It also seems to not have any issues if it's only 2 hidden video elements, it's only if there are more than 2. 

Edge also seems to be impacted on version 103. Versions 102 seemed to be fine.

Thank you for your time.

**Comment by manjeshbhargav** [comment]
Hi @gicuuu3 ,

Are you a Twilio Video customer who is using the SDK? I ask because we were able to reproduce this issue in our [video app](https://github.com/twilio/twilio-video-app-react). It turned out that this bug is happening because we clone the remote audio tracks to feed them to audio level indicators for the participants in the video session. Once we stopped cloning and re-use the same remote tracks for playback as well as audio level indicators, then everything worked as expected.

Thanks,

Manjesh

**Comment by timmydoza** [comment]
Hi @gicuuu3 - thanks for the issue!

As @manjeshbhargav said - we were able to reproduce this issue using our React Video App. It does not look like this issue has anything to do with removing video elements from the DOM. It does seem that audio is interrupted when a participant is removed from the page, and it appears that this is because the participants Audio Level Indicator component [stops a clone of the MediaStreamTrack](https://github.com/twilio/twilio-video-app-react/blob/master/src/components/AudioLevelIndicator/AudioLevelIndicator.tsx#L52) when it is removed from the page.

As far as we can tell, calling `.stop()` on a clone of an audio MediaStreamTrack from a remote peer is the root cause of the audio interruption in Chrome version 103. The issue can reproduced on this [WebRTC Demo](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) by following these steps:

1. Click "Start"
2. Click "Call"
3. Run this snippet in the JS console to clone and stop the audio MediaStreamTrack from the remote peer. If you are in Chrome 103, this snippet will cause the remote audio track to no longer be heard:
```
const clonedAudioMediaStreamTrack = document.getElementById('remoteVideo').srcObject.getAudioTracks()[0].clone();
clonedAudioMediaStreamTrack.stop();
```

In your video app where you experience this audio interruption, are you stopping any cloned MediaStreamTracks?

As a workaround in our React Video App, we can simply refrain from cloning and stopping the MediaStreamTracks used in the Audio Level Indicator component. The cloning was added as a workaround for an issue in iOS. We can add logic so that the MediaStreamTracks are only cloned on iOS, but not on other browsers. You can see the pull request with the workaround here: https://github.com/twilio/twilio-video-app-react/pull/713/files

Please let us know if any of this helps with your issue!

**Comment by gicuuu3** [comment]
Yes. I've verified things and indeed it is the cloning that causes that behavior. We clone for audio level indicators. Once I disabled the indicator behavior the interruptions stopped. Thank you for the help. 

Should I retitle this ticket to the actual cause so that it's easier for people to find? (not sure what's usually a good approach in these scenarios)
