### ISSUE TITLE
Default video disabling

### ISSUE THREAD

**Issue by cengizhanhakan** [twilio/twilio-video.js#1873]
Is there a way to create a localvideotrack with video is off. If I create the track then disable it, remoteParticipant doesn't get that first disable event

**Comment by PikaJoyce** [comment]
Hi @cengizhanhakan,

Thanks for the question. In what use case would you use this for? If you could create localvideotrack with the video off, you wouldn't get the disabled event either (because you never had to disable it). The best way is to create a local video track to ensure your video is working and then stopping it before joining the room, which you have mentioned.  Here's a link to the [best practices](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#acquiring-local-media), as well.

You can alternatively, create a localvideotrack, not attach the track to a `<video>` element and disable the track. That way, if a remoteParticipant is subscribed, they will get that disabled event but not see video. 

Best,
Joyce

**Comment by cengizhanhakan** [comment]
Hi @PikaJoyce, thank you for your response. With the growing trend in WFH, we want our clients to join the calls with their video disabled. 

So far we have tried 
- As soon as we create the video track we're disabling (Causes issues with emitting events in participants, enable/disable takes more than a few toggles.)

I will give the second recommendation a try and get back to you. Thanks.

**Comment by PikaJoyce** [comment]
Hi @cengizhanhakan,

Thanks for the response! That's understandable. Another suggestion is to simply not create a video track until after they've joined a room if the user decides to turn their camera on. 

You can also simply pass a [ConnectOptions](https://sdk.twilio.com/js/video/releases/2.24.0/docs/global.html#ConnectOptions__anchor) object to `connect` with `video: false` or simply omit it entirely.

After, if they want to turn on their cameras, you can then call `createLocalVideoTrack` and simply publish that track to the room after connecting.

```JavaScript
const connectOptions = {
    name: 'TheRoomName',
    audio: true,
    ... any other options
 };

// Connect to a Room with only audio
const room = await Video.connect(token, connectOptions);

// Adding video after connecting to a Room
const localTrack = await Video.createLocalVideoTrack();

room.localParticipant.publishTrack(localTrack);
```

Either way, please let me know how it works out! 

However, since it seems like there isn't anything that we can do from our side I will be closing this issue now. But I'm more than happy to continue our discussions on this thread if anything else arises! 

Best,
Joyce
