### ISSUE TITLE
Video freezes or browser crash with 3 or more participants

### ISSUE THREAD

**Issue by nidhisarvaiya** [twilio/twilio-video.js#19]
Hello,

We have been trying to use Twilio Video conference feature for one of our application.

We are facing few of the below mentioned issues in our application as well as in sample demo app provided by Twilio deployed on Heroku

One or more participant video stream freezes in ongoing video session randomly
One or more participant browser crashes randomly showing blank window. Once blank window pops up we are not even able to right click in window.
This issue happens if we have 3 or more participants joining video call.

Issue can be replicated in demo app deployed in Heroku

URL: https://twilio-demo-1.herokuapp.com/

Organizer can generate three sample access tokens in Twilio account and invite two participants to join the call using identifier of access tokens

Can somebody please help to resolve this issue.

Thanks,

**Comment by markandrus** [comment]
Hi @nidhisarvaiya,

The current Twilio Video SDKs use P2P mesh, which means for a 3-party video conference you will end up sending a copy of your video twice. By default, this will not be particularly performant, especially if your are sending HD video. Depending on your application, you may wish to reduce the size of the video you are sending in order to improve performance. For example, you can pass the following constraints when acquiring LocalMedia to constrain the size of the video sent:

```js
const videoConstraints = {
  width: {
    max: 320
  },
  height: {
    max: 240
  }
};
```

Very soon we will be making a media server available that should alleviate some of these performance issues, especially in Rooms with 3 or more Participants.

Best,
Mark
