### ISSUE TITLE
Invite link ?

### ISSUE THREAD

**Issue by muhamedoufi** [twilio/twilio-video.js#1913]
How to create invite link for twilio video room 

[Help Wanted]

**Comment by PikaJoyce** [comment]
Hi @muhamedoufi,

Thanks for opening this issue with us. You can simply tell another participant to join on your room name. Alternatively, this can also depend on how you've written your app. You can also pass the room name as a [url parameter](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get) thereby inserting the room name before connecting to a room. 

We have an example of this in use in our [quickstart](https://github.com/twilio/video-quickstart-js/blob/2734a083a8a2b3e77f1436d7cee8bc9ec18a94f0/quickstart/src/selectroom.js#L18-L19). 

Since there is no action items, I'll be closing this ticket. Let me know if you have any further questions!

Best,
Joyce

**Comment by muhamedoufi** [comment]
Thanks, but let's say I send you a link to enter into a conversation with me and the link looks like this: twilio.com/room=nameOfroom You will click on the link and enter the room with me. But in this way you can create a room for yourself that you do not have the right to. The advantage of the invite link is that you can never guess it because it will be like this twilio.com/hmgjrg53t533y6vevvgeggd#26
I hope you understand what I mean

**Comment by muhamedoufi** [comment]
> Hi @muhamedoufi,
> 
> Thanks for opening this issue with us. You can simply tell another participant to join on your room name. Alternatively, this can also depend on how you've written your app. You can also pass the room name as a [url parameter](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get) thereby inserting the room name before connecting to a room.
> 
> We have an example of this in use in our [quickstart](https://github.com/twilio/video-quickstart-js/blob/2734a083a8a2b3e77f1436d7cee8bc9ec18a94f0/quickstart/src/selectroom.js#L18-L19).
> 
> Since there is no action items, I'll be closing this ticket. Let me know if you have any further questions!
> 
> Best, Joyce

Thanks, but let's say I send you a link to enter into a conversation with me and the link looks like this: twilio.com/room=nameOfroom You will click on the link and enter the room with me. But in this way you can create a room for yourself that you do not have the right to. The advantage of the invite link is that you can never guess it because it will be like this twilio.com/hmgjrg53t533y6vevvgeggd#26
I hope you understand what I mean

**Comment by muhamedoufi** [comment]
@PikaJoyce 
Thanks, but let's say I send you a link to enter into a conversation with me and the link looks like this: twilio.com/room=nameOfroom You will click on the link and enter the room with me. But in this way you can create a room for yourself that you do not have the right to. The advantage of the invite link is that you can never guess it because it will be like this twilio.com/hmgjrg53t533y6vevvgeggd#26
I hope you understand what I mean

**Comment by PikaJoyce** [comment]
Hi @muhamedoufi,

I see, so what you're looking for is a personalized link/instance and not allow anyone with a link to your room to access it? If that's the case, you may have to look into deploying a new and unique link separately from how Twilio Video SDK. However, you can look into something like [serverless](https://www.twilio.com/docs/labs/serverless-toolkit) following this [blog post](https://www.twilio.com/blog/build-a-video-app-javascript-twilio-cli-quickly) in order to deploy a personalized instance quickly. 

Alternatively, you can also check out the [react app](https://github.com/twilio/twilio-video-app-react) as you can deploy your own applications easily with the cli to generate unique links as well. In the end, you'd have a link that looks something like
```
https://video-app-xxxx-yyyy-dev.twil.io/?passcode=11111111111111
```
And from there, you can join a room.

I hope that helps!
