### ISSUE TITLE
Twilio Programmable Video End of Life and Transition Plan

### ISSUE THREAD

**Issue by anna-vasilko** [twilio/twilio-video.js#2038]
### Twilio Programmable Video End of Life and Transition Plan

**What do you need to know?**
 
We know that Twilio Programmable Video is a key channel for many customer engagement use cases.  We also understand the importance of a seamless transition for our valued customers like you who utilize Twilio Programmable Video.

Listening to our customers’ feedback, we’ve extended the December 5, 2024 EOL date by two years, affirming our commitment to support you through this transition period.

The new Programmable Video end-of-life (EOL) date is now **[December 5, 2026](https://www.twilio.com/en-us/changelog/Extension-of-Twilio-Programmable-Video-End-of-Life-to-December-5-2026)** and you can continue to use Twilio Programmable Video until this date. Twilio will fully support the product until then.

Should you have any questions or need further clarification on how this extension may affect your use case or transition, please don’t hesitate to reach out directly to your Account Executive or Technical Account Manager, or refer to our [Twilio Help Center article](https://help.twilio.com/articles/24158233644443-Programmable-Video-End-of-Life-Extension). 

Sincerely, 

Team Twilio

**Comment by michalzaq12** [comment]
@anna-vasilko Will the Twilio Network Traversal Service (STUN/TURN) still be available? https://www.twilio.com/en-us/stun-turn

**Comment by anna-vasilko** [comment]
Hi, @michalzaq12, 
Yes, STUN/TURN is a standalone service and is not impacted by the Video EOL. It will continue being available after the Video EOL date.

**Comment by Talb2005** [comment]
I'll be happy to hear from other twilio-video users, what alternatives are you considering migrating to, other than the Zoom migration suggested by Twilio? 
Is anyone considering running their own Media Server for group calls?

**Comment by lingawarp** [comment]
Hey @Talb2005, a couple of folks have reached out to us at https://dyte.io. Sharing a couple of resources here - [Twilio video vs Dyte](https://dyte.io/twilio-video-competitor) and [Migration Guide](https://docs.dyte.io/guides/migration/twilio/concepts-twilio-vs-dyte).

**Comment by kwindla** [comment]
We have many happy ex-Twilio Video customers at Daily. We play nicely with Twilio in a bunch of ways, and have been building developer-focused WebRTC tooling since 2016. Our engineering team is the most experienced (and largest) WebRTC-focused team in the world, including engineers who are authors on the standards docs, active contributors to the libwebrtc and Mediasoup projects, etc.

Some notes about porting to Daily from Twilio:
- **Migration resources: https://www.daily.co/competitive/twilio-alternative/**
- We have the industry's **most extensive and high-performance global infrastructure** for WebRTC video and audio: https://www.daily.co/blog/infrastructure-week-at-daily-2023-edition/
- We understand enterprise customer's needs. You won't have to change your customers' TURN firewall rules when you port to us from Twilio, for example. **We are HIPAA and SOC 2 Type 2 compliant**.
- We offer **true end-to-end encryption** for use cases that require fully auditable e2e support.
- We have **SIP video and telephone dial-in and dial-out** support.
- We can provide **third-party benchmarking** showing that our call quality and netword adaptive code perform better for real-world users than all competitors including Vonage, Agora, Chime, and Zoom's Web SDK.
- **Daily supports all your video use cases**: 1:1 sessions, 100k participant real-time WebRTC sessions, live streaming egress to HLS and RTMP, programmable cloud compositing and post-processing recording workflows
- We are AI ready with terrific toolkits for building **voice-driven LLM apps, copilots, virtual characters, meeting summarization tools, and RAG video search**: https://www.daily.co/blog/ai-week-at-daily-2023-edition/

Finally, we know that you didn't have porting to a new video partner in your plan for 2024. We want to help. For Twilio enterprise customers, we offer a $25k credit that you can apply to your Daily bill or to engineering work with one of our implementation partners. We have close relationships with a number of excellent development shops, ranging from very large companies with a track record of delivering to Fortune 500 clients, to focused boutique shops that specialize in building communications apps for demanding use cases.

Feel free to contact sales@daily.co if you are evaluating your options to replace Twilio Programmable Video.

**Comment by binhduong85** [comment]
**Dear Github Developers Community,**

**If you are looking for solutions to solve CPaaS vendor locked-in with your streaming industry.**
Our open-source project specializes in providing low-latency streaming solutions for a broad spectrum of applications, all tailored to align with your business requirements. Powered by SAN-I/O, we offer a decentralized network infrastructure that ensures the delivery of high-quality data with minimal latency and cost-effective efficiency. This approach mirrors the strategy employed by Cloudflare for their network. As a result, enterprises can drastically cut down on deployment time and rapidly expand globally, all within minutes, at the most affordable cost.
**Some ideas about this project started from this point** https://github.com/8xFF/atm0s-sdn/blob/master/docs/smart_routing.md
Above is the starting point of the project. The most important thing to do is scale and optimize latency and stability.

**Features benefits**

- 🚀 Powered by Rust with memory safety and high performance.
- High availability by being fully decentralized, with no central controller.
- 🛰️ Private zone & Multi-zone support, high scalability.
- Support encodings: H264, Vp8, Vp9, H265 (Coming soon), AV1 (Coming soon)
- Cross platform: Linux, MacOs, Windows.
- Decentralized WebRTC SFU (Selective Forwarding Unit)
- Modern, full-featured client SDKs Vanilla Javascript, Rust, React, React Native, Flutter, iOS Native, Android Native
- Easy to deploy: single binary, Docker, or Kubernetes
- Advanced features including:
-  Audio Mix-Minus (WIP)
-  Simulcast/SVC
-  SFU
-  SFU Cascading (each stream is a global PubSub channel, similar to [Cloudflare interconnected network](https://blog.cloudflare.com/announcing-cloudflare-calls/))
-  Recording
-  RTMP
-  SIP (WIP)
-  WebRTC
-  Whip/Whep

For more details about our project, please visit our GitHub page at https://github.com/8xFF or https://github.com/8xFF/atm0s-media-server (Decentralized Media Server)
Feel free to contact with us via [hello@8xff.io](mailto:hello@8xff.io) if you have ideas for collaboration with our team
Merry Christmas and a happy new year 2024 to you all !
Best Regards,
8xFF Team

**Comment by shoaib-iqbal** [comment]
I am working on migration from twillio to zoom, if any one else is working on it let's plan it together

**Comment by robertstrobl** [comment]
> I'll be happy to hear from other twilio-video users, what alternatives are you considering migrating to, other than the Zoom migration suggested by Twilio? Is anyone considering running their own Media Server for group calls?

@Talb2005 you may want to consider Digital Samba https://www.digitalsamba.com/blog/a-straightforward-guide-to-migrating-from-twilio-to-digital-samba

**Comment by alexandermaisey** [comment]
> I'll be happy to hear from other twilio-video users, what alternatives are you considering migrating to, other than the Zoom migration suggested by Twilio? Is anyone considering running their own Media Server for group calls?

I suggest Dyte.  They have an excellent shim with one-to-one functionality.  https://dyte.io/blog/migrate-twilio-video-dyte-shim/

**Comment by alexandermaisey** [comment]
@anna-vasilko Will the PreFlight test library still function?

**Comment by shoaib-iqbal** [comment]
I have successfully upgraded Twillio to Zoom video SDK

**Comment by Talb2005** [comment]
@anna-vasilko 
I understand the the EOL date has been extended to December 5, 2026. 
https://www.twilio.com/en-us/changelog/Extension-of-Twilio-Programmable-Video-End-of-Life-to-December-5-2026

Shouldn't this important update be reflected in this issue?

**Comment by donaltoomey** [comment]
@Talb2005 thanks for that. The issue has been updated to reflect the extension and new date.

**Comment by donaltoomey** [comment]
Hi folks, Twilio Video is open for business again. Additional details are below:
- https://www.twilio.com/en-us/changelog/-twilio-video-will-remain-a-standalone-product
- https://www.twilio.com/en-us/blog/twilio-video-update-2024
- https://www.twilio.com/en-us/video
