### ISSUE TITLE
Error on submission to App Store: twilio-video contains bitcode

### ISSUE THREAD

**Issue by sigaits** [twilio/twilio-video.js#2059]
I've been using twilio-video and other Twilio services/SDKs in my React Native apps for a while now, but on my recent submission to the App Store (through EAS build/submit), the submission fails consistently with an error message "twilio-video contains bitcode".

I've tried everything I could think of, and find on the web to work around it, but nothing works, short of the suggestion to strip out bitcode from the podfile. But that won't work for me because I'm building and submitting through EAS, not local builds. And Expo support hasn't been helpful so far.

I understand that Apple has deprecated bitcode but is this library going to comply with it soon?

 - [ x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Software versions:**

 - [ ] Browser(s):
 - [x] Operating System: MacOS Sequoia 15.1
 - [x] twilio-video.js: 2.28.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Expo 51.0.38, React Native 0.74.5, react-native-twilio-video-webrtc: 3.2.0

**Comment by luisrivas** [comment]
Hi @sigaits, I am glad you are building your product using Twilio's technologies. However, you are using https://github.com/blackuy/react-native-twilio-video-webrtc, which is an unofficial react-native library created by the community based on our SDK for iOS and Android. I saw you already found a good conversation in which the maintainer of this library is participating (https://github.com/blackuy/react-native-twilio-video-webrtc/issues/750), so I will close this issue since this repository is for web-specific implementation.
