### ISSUE TITLE
Inverted Video

### ISSUE THREAD

**Issue by CarlosUvaSilva** [twilio/twilio-video.js#210]
is the video supposed to be mirrored?
I can't get the video to work "normally", it always shows inverted either in React or React Native

**Comment by markandrus** [comment]
Hi @CarlosUvaSilva,

Could you include a screenshot or example of what you mean? It can be tricky to talk about how video should "normally" display, since some apps will reflect the video about the Y-axis and some apps won't. If you use twilio-video.js's APIs for creating LocalVideoTracks, we're just calling `getUserMedia` and using whatever the platform provides us. If you want to reflect the video, you might be able to use the following:

```css
video {
  transform: scaleX(-1);
}
```

Best,
Mark

**Comment by CarlosUvaSilva** [comment]
@markandrus that solved the problem, thanks!
