### ISSUE TITLE
[1.6.0] Multi-platform testing (Android-to-iOS failure)

### ISSUE THREAD

**Issue by stvnmntjy** [twilio/twilio-video.js#238]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Software versions:**

 - [x] Browser(s): Mobile Safari 11, Chrome for Android 63, Chrome 63
 - [x] Operating System: OSX, Android, iOS
 - [x] twilio-video.js: 1.6.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Angular >1 and Ionic 2

Working on a multi-device, cross-platform (Android, iOS, desktop) app with WebRTC video capabilities, all using twilio-video.js.

Rooms are private, two-user P2P.

This does relate to https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md#safari.

There are questions, based upon the testing below, afterward. Twilio feedback is appreciated.

## Test Scenarios:

Users:

1. Participant 1  (P1)
1. Participant 2 (P2)

Endpoints:
1. Web
1. Android (* running video in Chrome for Android, **not** WebView)
1. iOS (* running video in Mobile Safari 11, **not** UIWebView, etc.)

The rooms are created server-side, with no video codec preference(s) specified.

Android and iOS are running the same server-served "video page" (i.e. there is **no** difference in the HTML and JS they run).

The Web runs in an Angular >1 app.

(side note: Android-to-Android and iOS-to-iOS work fine. Those results are not pertinent to the issue, so are absent.)

### Test 1:

1. P1 (Web) joins Room.
2. P2 (Android) joins Room.

Result: Good.

### Test 2:

1. P2 (Android) joins Room.
2. P1 (Web) joins Room.

Result: Good.

### Test 3:

1. P1 (Web) joins Room.
2. P2 (iOS) joins Room.

Result: Good.

### Test 4:

1. P2 (iOS) joins Room.
2. P1 (Web) joins Room.

Result: Good.

### Test 5:

1. P1 (iOS) joins Room.
2. P2 (Android) joins Room.

Result: Twilio Error [53400](https://www.twilio.com/docs/api/errors/53400) reported from desktop Safari (debugging for iOS). No errors reported in desktop Chrome (debugging for Android). Neither see remote participant's video.

### Test 6:

1. P2 (Android) joins Room.
2. P1 (iOS) joins Room. 

Result: Twilio Error [53400](https://www.twilio.com/docs/api/errors/53400) reported from desktop Safari (debugging for iOS). No errors reported in desktop Chrome (debugging for Android). Neither see remote participant's video.

## Question(s):

1. Since tests 1-4 _suggest_ neither the web nor _mobile client_ know which video codec of the track the other is sending, but can decode each other's correctly, regardless of who's first in, why doesn't this work for tests 5 and 6?

1. Supposing Mobile Safari **only** sends H.264 and **only** works with (receiving) H.264, and supposing Chrome for Android **only** sends VP8 and **only** works with (receiving) VP8, why do they both negotiate the Web remote participant's codec -- regardless of which video codec the Web participant uses or when they joined? 

(side note: We specify ("prefer") H.264 for Web but, really, does that matter considering the test results?)

_I only mention codecs because that seems to be what the community discusses as a roadblock to WebRTC interop, so if this is not an issue with twilio-video.js, please say so._ 

Can someone explain why Android-to-iOS (and vice versa) isn't working when apparently it should be? Or shouldn't it?

**Comment by markandrus** [comment]
Hi @stvnmntjy,

Thanks for the detailed report, and sorry for the delay in responding.

> 1. Since tests 1-4 suggest neither the web nor mobile client know which video codec of the track the other is sending, but can decode each other's correctly, regardless of who's first in, why doesn't this work for tests 5 and 6?

Without looking at logs, here is my guess at what codecs the three platforms you tested support:

| | Web | Android | iOS |
|:---: | :---: |:---: |:---: |
| H.264 | ✓ | | ✓ |
| VP8 |  ✓ | ✓ | |

Tests 5 and 6 should fail because neither Android nor iOS support a common codec:

| | Web | Android | iOS |
|:---: |:---: |:---: |:---: |
| Web | | | |
| Android | | | x |
| iOS | | x | |

> Result: Twilio Error 53400 reported from desktop Safari (debugging for iOS). No errors reported in desktop Chrome (debugging for Android). Neither see remote participant's video.

This is strange and should not happen. Can you provide a Room SID?

> 2. Supposing Mobile Safari only sends H.264 and only works with (receiving) H.264, and supposing Chrome for Android only sends VP8 and only works with (receiving) VP8, why do they both negotiate the Web remote participant's codec -- regardless of which video codec the Web participant uses or when they joined?

Likely the Web Participant supports both H.264 and VP8. In this case, the Web and Android or iOS Participant will negotiate the intersection of supported codecs (just VP8 or just H.264, respectively).

> (side note: We specify ("prefer") H.264 for Web but, really, does that matter considering the test results?)

The preferences apply _after_ negotiating the intersection of supported codecs. So if a Participant supports both H.264 and VP8, prefers H.264, but then negotiates with a Participant who only supports VP8, there preference will not apply since the intersection contains only VP8. If, however, both Participants support H.264 and VP8, and one prefers H.264 and the other prefers VP8, they _will_ send their preferred codec. Does that make sense?

**Comment by markandrus** [comment]
@stvnmntjy if you're still having issues, feel free to re-open this issue or a new one. You may also email support@twilio.com.

Best,
Mark

**Comment by vladimirmoushkov** [comment]
I still have interoperability issues with iOS (Safari v12) and Chrome Desktop v71.

I get perfect video from Chrome but the Safari is not even showing attempt to show video. The logs says:
TwilioError: No supported codec video

My room type is group-small (but tried also with peer-to-peer and have the same problem).
Room codecs preferences are not set as well client side video prefs are not set but did tried to set  VP8,VP9 and H264 as leading ones and does not change a bit.

My question was anyone able to make latest iPhone to work with latest Chrome desktop browser?

**Comment by vladimirmoushkov** [comment]
I retract my problem submission as found a solution for my case. Since we need just two users we could use 'peer-to-peer' as specified here:
https://user-images.githubusercontent.com/359154/30874068-1fdc6eba-a2a4-11e7-871f-4547ab594e4c.png
and then ensure that room created are "peer-to-peer". This makes iOS to iOS, iOS to Chrome, iOS to Safari - works like a charm.
