### ISSUE TITLE
Failed to publish the LocalAudioTrack: The LocalAudioTrack was unpublished

### ISSUE THREAD

**Issue by tillkruss** [twilio/twilio-video.js#262]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.

**Code to reproduce the issue:**

```js
room.localParticipant.unpublishTrack(track);
```

**Issue:**

When a user toggles a track on and then off really fast, they get the following error.

There seems to be no way for me to catch the `Error` in that promise. What do you guys recommend to handle this case?

```
WARN in [LocalParticipant #1: PA50d18a430034f829daf2eeecb8581ff2]: Failed to publish the LocalAudioTrack: The [LocalAudioTrack #3: 6a1e38c5-006a-4020-9fad-4f3e086aa6cd] was unpublished

Uncaught (in promise) Error: The [LocalAudioTrack #3: 6a1e38c5-006a-4020-9fad-4f3e086aa6cd] was unpublished
```

TODO

**Software versions:**

 - [x] Browser(s): Google Chrome 63.0.3239.132
 - [x] Operating System: macOS 10.13.3
 - [x] twilio-video.js: 1.7.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue.js

**Comment by markandrus** [comment]
Hi @tillkruss,

Sorry you're having this issue. So I guess what may be happening is something like

```js
const promise = room.localParticipant.publishTrack(track); // Pending Promise
room.localParticipant.unpublishTrack(track);
// Promise rejects, WARN, and "Uncaught (in promise) Error"?
```

If you add a `catch` handler to `promise`, does "Uncaught (in promise) Error" go away? I expect twilio-video.js will still WARN. We may be able to remove that.

The issue is that `promise` should resolve to a LocalTrackPublication if-and-only-if the LocalTrack successfully published. If `promise` hasn't resolved yet, `unpublishTrack` will "cancel" it, resulting in a rejection. We could let `unpublishTrack` "queue up" until `promise` resolves (or rejects), but this may not be desirable.

An alternative is to let your app `unpublishTrack` only when the `promise` resolves to a LocalTrackPublication. You could also call `unpublish` on the LocalTrackPublication itself. So, for example, if you had some code like

```js
const track; // ...

button.onclick = () => {
  if (room.localParticipant.tracks.has(track.id)) {
    room.localParticipant.unpublishTrack(track);
  } else {
    room.localParticipant.publishTrack(track);
  }
};
```

You could write it like this

```js
const track; // ...
let promise = Promise.resolve();

button.onclick = async () => {
  const publication = await promise;
  if (publication) {
    publication.unpublish();
  }
  promise = room.localParticipant.publishTrack(track);
};
```

Does that help?

Mark

**Comment by tillkruss** [comment]
Super helpful, thanks!
