### ISSUE TITLE
How can I do Face Detection on a RemoteVideoTrack with OpenCV and Python?

### ISSUE THREAD

**Issue by moonis007** [twilio/twilio-video.js#333]
i need to integrate twilio video webcam feed with opencv for face detection . could you please help me to integrate webcam feed with opencv python

**Comment by markandrus** [comment]
Hi @moonis007,

If you want to do face detection on a LocalVideoTrack or RemoteVideoTrack you have a couple options. 

**Face Detection With Python**

Since your Python server will do the analysis, you'll need to "take a snapshot" of the LocalVideoTrack or RemoteVideoTrack and send it up to your server. To do this, you can follow the [`localvideosnapshot`](https://github.com/twilio/video-quickstart-js/tree/master/examples/localvideosnapshot) example in the [`twilio/video-quickstart-js`](https://github.com/twilio/video-quickstart-js) project. If you setup and run that project, you can go to [http://localhost:3000/localvideosnapshot](http://localhost:3000/localvideosnapshot) to see it in action.

You'll need to take a stream of snapshots and send them up to your Python server for analysis, either via WebSocket messages or HTTP requests.

**Face Detection With JavaScript**

If you can get away with doing the face detection client-side, it might be simpler to use [`auduno/clmtrackr`](https://github.com/auduno/clmtrackr). Actually, they already even have an example of [tracking in video](https://www.auduno.com/clmtrackr/examples/clm_video.html). It should be straightforward to hook up twilio-video.js to this example.

**Comment by markandrus** [comment]
Hi @moonis007,

I'm going to close this issue, but feel free to write back or reopen if you have any other questions.

Mark
