### ISSUE TITLE
TwilioError: Participant not found

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#340]
Hi,

What could be the reason(s) for getting "Participant not found" error? We've noticed this error a few times on Sentry. It is preventing users from sharing their screen & webcam because they cannot connect to Twilio.

Thanks

**Comment by innerverse** [comment]
Hi @katranci,

I apologize that you're running into this.  A `53204 - Participant not found` error happens when a message arrives at our servers after the Participant has already been disconnected.  Think of it as an HTTP 404.  There are many reasons - a race condition on the wire between attempting to change media and an explicit disconnect, another Participant joining with the same identity (this will remove the first Participant from the same room with that identity), etc.  

If you scroll up a little higher in the log, you'll usually see the root cause for the disconnect.  Often this is `53205 - Participant disconnected because of duplicate identity` etc.  If you can share a couple RoomSids, we can help investigate where things are going wrong.

We are aware that our error documentation could use an overhaul to help make this easier to understand.  Thanks for the reminder.

Thanks,
Seth @ Twilio

**Comment by katranci** [comment]
Hi @innerverse,

The room sid is RMf90f662da36eecbd9eacf550f0241d7e

Thanks

**Comment by innerverse** [comment]
Hi @katranci 

I just looked into your specific RoomSid, RMf90f662da36eecbd9eacf550f0241d7e, and it looks like you're running into a timeout bug with our outer region Media Servers.  We have seen some cases where the heartbeat between our `us1` signaling servers is set too aggressively for Media Servers in other regions, leading to a disconnect in the Room.  We've made improvements in this area today for exactly this case-- Let me know if it is better for you.  

Thanks,
Seth

**Comment by innerverse** [comment]
@katranci 
We've made several improvements in this area on the backend and you should no longer be running into this issue.   

In your particular room, it would have lead to a Room "vanishing" for your participants and media to no longer work until the Room was completed.  We now will recover the Room on the server side if this happens.  For your other questions, look out for our new Network Quality API currently under development and disconnect status, which will allow you to differentiate a REST API disconnect from other disconnects.
