### ISSUE TITLE
Issues with publishing video tracks

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#377]
Hi,

Could you help me investigate issues in room RM7b30cc5b4ab273e8f69a99b021f3ddcd? Here is what I managed to collect from our logs:

2018-07-16 10:04:54.827Z PAf547b6c30d11e7ceb5c0c7c1889bba96 publishes his webcam successfully
2018-07-16 10:32:08.286Z PAf547b6c30d11e7ceb5c0c7c1889bba96 stops his webcam

At this point all participants should have received Room#trackRemoved event and disconnected from Twilio room due to no tracks being present in the room. I can see the two subscribers disconnected fine but couldn't see it for the publisher.

2018-07-16 10:37:07.886Z PAf547b6c30d11e7ceb5c0c7c1889bba96 tries to publish his webcam again but it looks like the attempt gets stalled in a way. Is there a chance that Room.localParticipant.publishTrack API takes a very long time to settle or never settles?

2018-07-16 10:37:57.216Z PAf547b6c30d11e7ceb5c0c7c1889bba96 shares his screen but the other participants cannot see it. Are the publisher and subscribers in two different rooms somehow?

Thanks

**Comment by katranci** [comment]
Could you also look into room RMa26e415e78eab7d03bfd5ce60260613e for a separate problem. Not sure what is happening exactly but it looks like the screenshare publisher's connection goes from disconnected to connected state but her publication wasn't recovered successfully? Hope these Sentry logs help:

```
2018-07-17 12:17:05.320Z | DEBUG in [object Object]: ICE connection state is "disconnected"

Tue Jul 17 2018 08:17:06 GMT-0400 (Eastern Daylight Time) | sip.transport | sending WebSocket message:

2018-07-17 12:17:08.000Z | DEBUG in [object Object]: ICE connection state is "connected"

2018-07-17 12:17:08.000Z | DEBUG in [object Object]: ICE connection state is "completed"

Tue Jul 17 2018 08:17:13 GMT-0400 (Eastern Daylight Time) | sip.transport | sending WebSocket message:

UPDATE sip:172.18.1.138:443;transport=wss SIP/2.0
Via: SIP/2.0/WSS ocl6kt6uk028.invalid;branch=z9hG4bK4994006
Max-Forwards: 70
To: <sip:orchestrator@endpoint.twilio.com>;tag=53346568_6772d868_f62b7e25-913d-4635-9b85-204c145f5671
From: <sip:4829ecc7-2f05-46b2-93da-a5a4bea7c55c@endpoint.twilio.com>;tag=gg2sogvgj9
Call-ID: s1kaf91jft7fg75ki0h6
CSeq: 6654 UPDATE
Session-Expires: 120
Supported: outbound, room-signaling, timer
User-Agent: SIP.js/0.7.7
Content-Length: 0

Tue Jul 17 2018 08:17:16 GMT-0400 (Eastern Daylight Time) | sip.ua | user requested closure...

Tue Jul 17 2018 08:17:16 GMT-0400 (Eastern Daylight Time) | sip.ua | closing registerContext

Tue Jul 17 2018 08:17:16 GMT-0400 (Eastern Daylight Time) | sip.registercontext | already unregistered message

Tue Jul 17 2018 08:17:16 GMT-0400 (Eastern Daylight Time) | sip.registercontext | already unregistered
```

**Comment by katranci** [comment]
There is one more session with problems. The organiser shared his screen several times but the other participants couldn't see it. I think room sid is RMdda2e24a891bda3402f6919c8ec3ac9c.

**Comment by manjeshbhargav** [comment]
@katranci 

Thank you for reaching out to us with your issue. We are in the process of investigating it and we'll reach out to you with our findings.

Thanks,
Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@katranci ,

From reading the logs for Room "RM7b30cc5b4ab273e8f69a99b021f3ddcd", it looks like:
* 2018-07-16T10:04:54.761Z: P1[PAf547b6c30d11e7ceb5c0c7c1889bba96] publishes "webcam" VideoTrack.
* 2018-07-16T10:04:56.703Z: P2[PAd2b1f1255bd4aebf23a93e86ac18d075] subscribes to the "webcam" VideoTrack.
* 2018-07-16T10:05:18.378Z: P3[PAcf4a70bc3df12cf4b2109e5117823949] subscribes to the "webcam" VideoTrack.
* 2018-07-16T10:29:20.315Z: **P3, and not P1** unpublishes it's "webcam" VideoTrack.
* 2018-07-16T10:31:20.369Z: P1 _starts_ publishing another VideoTrack.
* 2018-07-16T10:32:16.626Z: P1's ICE connection fails.
* 2018-07-16T10:32:22.742Z: P1 gets disconnected from the Room due to a `SignalingConnectionTimeoutError` (code: 53002).

It looks like the the process of publishing P1's second VideoTrack is aborted due to it being disconnected from the Room because of its inability to maintain a signaling connection with Twilio.

Let me know if this information is consistent with your observations. Also, it would be great if you can share a code snippet that describes your app logic.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@katranci ,

For Room "RMa26e415e78eab7d03bfd5ce60260613e", do you know which Participant experienced the ICE re-connection? It will help me narrow down the Participant SID in the logs.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by manjeshbhargav** [comment]
@katranci ,

For Room "RMdda2e24a891bda3402f6919c8ec3ac9c", did the subscribers see a `<video>` element with black frames, or did they not see the `<video>` element at all? According to the logs, all Participants in this Room were able to subscribe to all published VideoTracks.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks for getting back @manjeshbhargav 

For Room "RMa26e415e78eab7d03bfd5ce60260613e" the participant is PA8762a3c2bf85fbd2ceedb2696d9152b7
