### ISSUE TITLE
v2 release date

### ISSUE THREAD

**Issue by KayakinKoder** [twilio/twilio-video.js#378]
Just a question -- do you have a rough guesstimate of when v2.x is expected? Even a very rough guess would help us a lot with planning, thanks.

**Comment by markandrus** [comment]
Hi @KayakinKoder,

We've recently cut a [2.0.0-rc1](https://github.com/twilio/twilio-video.js/tree/2.0.0-rc1) release candidate in anticipation of our first 2.0.0-beta1 release. We think can have a 2.0.0-beta1 available on the CDN and in NPM around the end of next week.

Please test the betas! We're releasing a new major version not due to any significant new features, but because certain breaking API changes will better enable us to deliver some new features in the long-term. That being said, if we've removed an API in a 2.0.0-beta release that you really need, please let us know so that we can work to accommodate you before the proper 2.0.0 is released. The exact release date will depend on signals we get from customers, but I can imagine us having a release by early- to mid-September. Ideally, we'd go through no more than 3 beta releases.

**About 2.x**

The primary changes in 2.0.0 will be

1. **Removal of APIs that were [deprecated](https://github.com/twilio/twilio-video.js/blob/2.0.0-rc1/CHANGELOG.md#deprecations) in 1.12.0.** Please see the [migration guide](https://github.com/twilio/twilio-video.js/blob/2.0.0-rc1/CHANGELOG.md#migration-guide) included in the CHANGELOG.md. The biggest change to pay attention to is removal of RemoteTrack IDs. Please use Track `name` or `sid` instead.
2. **Changes to the types of Track collections on Participants.** Instead of collections like `Map<Track.SID, RemoteTrack>` on RemoteParticipants, you'll have `Map<Track.SID, RemoteTrackPublication>`. The original RemoteTrack can be accessed on the RemoteTrackPublication via the `track` property; however, this property is nullable, which works better with upcoming Track subscription APIs.

We'll also publish a Migration Guide on twilio.com, as well as share PRs against our QuickStart/Example projects that add support for the 2.0.0 APIs. These should help in updating.

**About 1.x**

We will continue to support and patch bugs in the 1.x release line. In general, we'll always support the last two major versions of twilio-video.js.

---

Please share any questions or concerns in this thread.

Thanks!
Mark

**Comment by manjeshbhargav** [comment]
Hi @KayakinKoder ,

We have released `twilio-video@2.0.0-beta1`. You can install it using _NPM_:

```
npm install twilio-video@2.0.0-beta1`
```

or include it in your webpage from our [CDN](http://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta1/twilio-video.min.js).

Please refer to the [2.x Migration Guide](https://www.twilio.com/docs/video/migrating-1x-2x) to migrate your app to the 2.x APIs. Let us know if you have any questions or experience any issues.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by KayakinKoder** [comment]
Awesome, thanks a lot.
