### ISSUE TITLE
Use cases for trackPublished and trackUnpublished events on RemoteParticipant

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#391]
Hi,

We are currently using [trackSubscribed](https://media.twiliocdn.com/sdk/js/video/releases/1.13.0/docs/RemoteParticipant.html#event:trackSubscribed__anchor) and [trackUnsubscribed](https://media.twiliocdn.com/sdk/js/video/releases/1.13.0/docs/RemoteParticipant.html#event:trackUnsubscribed__anchor) events on [RemoteParticipant](https://media.twiliocdn.com/sdk/js/video/releases/1.13.0/docs/RemoteParticipant.html) to attach/detach remote tracks shared by other participants in the room. However, we are not using `trackPublished` and `trackUnpublished` events anywhere. What are the use cases for these events?

Thanks

**Comment by manjeshbhargav** [comment]
Hi @katranci ,

"trackPublished" is emitted on a RemoteParticipant when it successfully publishes a RemoteTrack after joining a Room, where as "trackSubscribed" is emitted when the LocalParticipant successfully subscribes to a RemoteParticipant's published RemoteTrack.

Since we are moving towards allowing clients to be able to subscribe to RemoteTracks, "trackPublished" and "trackUnpublished" events help to keep track of published RemoteTracks (through their corresponding RemoteTrackPublications).

So, the order of events fired when a RemoteParticipant _publishes_ a RemoteTrack is:

```js
// "trackPublished" is fired first.
remoteParticipant.on('trackPublished', remoteTrackPublication => {
  // If successfully subscribed to, "subscribed" is fired second.
  remoteTrackPublication.on('subscribed', remoteTrack => {...});

  // If failed to subscribe to, "subscriptionFailed" is fired second.
  remoteTrackPublication.on('subscriptionFailed', error => {...});
});

// If successfully subscribed to, "trackSubscribed" is fired third.
remoteParticipant.on('trackSubscribed', (remoteTrack, remoteTrackPublication) => {...});

// If failed to subscribe to, "trackSubscriptionFailed" is fired third.
remoteParticipant.on('trackSubscriptionFailed', (error, remoteTrackPublication) => {...});
```

And the order of events fired when a RemoteParticipant _unpublishes_ a RemoteTrack is:

```js
remoteParticipant.on('trackPublished', remoteTrackPublication => {
  //"unsubscribed" is fired first.
  remoteTrackPublication.on('unsubscribed', remoteTrack => {...});
});

// "trackUnsubscribed" is fired second.
remoteParticipant.on('trackUnsubscribed', (remoteTrack, remoteTrackPublication) => {...});

// "trackUnpublished" is fired third.
remoteParticipant.on('trackUnpublished', remoteTrackPublication => {...});
```

However, if a RemoteParticipant _disconnects_ from the Room, the order of events fired is:
* "unsubscribed" on each RemoteTrackPublication of the RemoteParticipant
* "trackUnsubscribed" on the RemoteParticipant for each published RemoteTrack

For more details, please refer to the [RemoteTrackPublication Guide](https://github.com/twilio/twilio-video.js/blob/1.13.1/CHANGELOG.md#1100-may-30-2018).

Hope this helps clarify things.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by katranci** [comment]
Thanks for the clarification @manjeshbhargav.

If a remote participant (P1) has had publications already by the time another participant (P2) joins, then would P2 receive P1's tracks through `trackSubscribed` events or do I need to access them by retrieving the remote participants from `Room.participants` and calling `trackPublications` on P1?

Also, when `trackSubscriptionFailed` is emitted, is there any mechanism to retry subscribing? I'm imagining a scenario where a participant cannot subscribe to remote tracks due to a very short network glitch. I'm aware that there are multiple reasons that can cause `trackSubscriptionFailed` to be emitted but it would be nice to have list of these reasons and possible ways of recovering from them.

Thanks

**Comment by katranci** [comment]
Thanks a lot @manjeshbhargav, really appreciate the quick response 👍
