### ISSUE TITLE
TwilioError: Signaling connection disconnected

### ISSUE THREAD

**Issue by katranci** [twilio/twilio-video.js#401]
Hi,

We have started logging unexpected disconnects recently. I did a quick count and it seems like there are 90 of them in the last 3 days. I've listed some of them below. Why are there so many of them?

Thanks

| Date                         | Room                               | LocalParticipant                   | TwilioError                       |
| ---------------------------- | ---------------------------------- | ---------------------------------- | --------------------------------- |
| Aug 13, 2018 2:30:29 PM UTC  | RMb21bfbf3239ee4ff68bbf30290d7950e | PAc8417b538685edd3a25c55aff1c9c2f6 | Signaling connection disconnected |
| Aug 13, 2018 9:06:39 AM UTC  | RM117638e6078d84afa60ddbf312dca0bd | PA754a03df14c4df53ea5a52a03e91d682 | Signaling connection disconnected |
| Aug 13, 2018 9:17:35 AM UTC  | RM894ca64e1a646d61fb21d2e070c94e4f | PAbe6a9007a02e0878fea45c4ede762694 | Signaling connection disconnected |
| Aug 13, 2018 12:24:44 PM UTC | RMc4b650dbcef567673ed00f82b2e9b0b7 | PA0c2d35dea3003c27eb64cccea5fb0cb7 | Signaling connection disconnected |
| Aug 13, 2018 12:24:45 PM UTC | RMc4b650dbcef567673ed00f82b2e9b0b7 | PA760e6412fc42c4b784b568cd1dffd761 | Signaling connection disconnected |
| Aug 13, 2018 12:50:18 PM UTC | RM8bb0af003658e4e44d7ea69d6cbc13b3 | PAb744214127dd4aa194291a87350d1f70 | Signaling connection disconnected |
| Aug 13, 2018 12:59:00 PM UTC | RM8bb0af003658e4e44d7ea69d6cbc13b3 | PA2dd14be8752da7226d6a85b5880b7265 | Signaling connection disconnected |
| Aug 13, 2018 2:10:30 PM UTC  | RM70dc9300e57c5e3692cd7195310431f4 | PA2365202dd4448962acbca21a06964f45 | Signaling connection disconnected |
| Aug 13, 2018 2:16:53 PM UTC  | RM70dc9300e57c5e3692cd7195310431f4 | PAfb85949c98b45ee0355d0d54111edb8b | Signaling connection disconnected |
| Aug 13, 2018 2:20:26 PM UTC  | RM22ea73ff856fcead39b2e4f2459e8a0b | PAa5dca2a5544c34322a532261bacad161 | Signaling connection disconnected |
| Aug 13, 2018 2:36:03 PM UTC  | RM38e3d051b2aa9b49c5092c6229c68941 | PAd0676590677e8ac8937944041442ccc1 | Signaling connection disconnected |
| Aug 13, 2018 3:07:45 PM UTC  | RM21fe28f8ea1afb9b4393e8997307c5b3 | PA82e2375cb4a90babc18bdff2a07a6b29 | Signaling connection disconnected |
| Aug 13, 2018 3:08:44 PM UTC  | RM21fe28f8ea1afb9b4393e8997307c5b3 | PA2735c78508410da3e84c453e74f7cd12 | Signaling connection disconnected |
| Aug 13, 2018 3:26:20 PM UTC  | RM3703d577b0dc2ab55b498eb89992ae56 | PA4fa2003d3d1db9d66c9c0052faf365e2 | Signaling connection disconnected |
| Aug 13, 2018 3:53:09 PM UTC  | RM21fe28f8ea1afb9b4393e8997307c5b3 | PA5bd62b6467f4b39c69fe0d92412db9fe | Signaling connection disconnected |
| Aug 13, 2018 4:01:49 PM UTC  | RM21fe28f8ea1afb9b4393e8997307c5b3 | PAd157fb4f3d144bd8e2685e03de4b1717 | Signaling connection disconnected |
| Aug 13, 2018 4:01:50 PM UTC  | RM21fe28f8ea1afb9b4393e8997307c5b3 | PAae9f52710b11b453f0e8dcc618d70d0f | Signaling connection disconnected |
| Aug 13, 2018 4:17:31 PM UTC  | RM21fe28f8ea1afb9b4393e8997307c5b3 | PAe8abd0e4b9832abadbe09e8382874704 | Signaling connection disconnected |
| Aug 13, 2018 4:34:10 PM UTC  | RMcd0eda9400452370fd7916ee520c835e | PAb9cc5d9b5bc4e892f392f8cb9043e0c8 | Signaling connection disconnected |
| Aug 13, 2018 5:07:42 PM UTC  | RMdfed389fddbdd6e7d7441c62ab376431 | PA10ca11a652a51083e9444c3325521c2e | Signaling connection disconnected |
| Aug 13, 2018 5:24:01 PM UTC  | RMdfed389fddbdd6e7d7441c62ab376431 | PA7e07e8b7d33d6d1faf9707fbcc04ff28 | Signaling connection disconnected |
| Aug 13, 2018 5:24:25 PM UTC  | RMdfed389fddbdd6e7d7441c62ab376431 | PA0dfef004299a57d45eef206a35241ac3 | Signaling connection disconnected |
| Aug 13, 2018 5:31:39 PM UTC  | RMdfed389fddbdd6e7d7441c62ab376431 | PA6cc722eeed252f38c3b3848e6a5ae9c5 | Signaling connection disconnected |
| Aug 13, 2018 5:44:26 PM UTC  | RMdfed389fddbdd6e7d7441c62ab376431 | PA4950758018e54a762ba5a5337bb3489f | Signaling connection disconnected |
| Aug 13, 2018 6:59:28 PM UTC  | RMe9f4d73b631ba9175b2cdfbc4f221f9a | PA309b754a0472f37ae874e6e445beacd8 | Signaling connection disconnected |
| Aug 13, 2018 11:24:42 PM UTC | RM9d146d6585ac77f021344a5db152dcd7 | PA42d8109a842597cc270b202b6ae7d4a9 | Signaling connection disconnected |
| Aug 14, 2018 2:24:38 PM UTC  | RM92cf6749391a454d26eea05ade589431 | PA5433fc67c47394811a30ad178dbc94a6 | Signaling connection disconnected |

**Comment by markandrus** [comment]
Hi @katranci,

I took a look at our logs for these Participant SIDs. Three of the disconnects were initiated by the server. Clients connected to our signaling server are required to send a "ping" (really, a SIP UPDATE) every 60 s. Missing a ping will result in a disconnect. Two of the three Participants that were disconnected by the server experienced ICE failures, so it's possible these Participants temporarily lost network connectivity and failed to send the necessary pings.

For the client-side disconnects, these include a "Signaling connection disconnected" message, which means they are coming from [here](https://github.com/twilio/twilio-video.js/blob/1.13.1/lib/signaling/v2/transport.js#L488). This code is executed when `session` emits "failed" or "bye" (neither of these are occurring, because we've already connected to a Room and we aren't receiving a SIP BYE) or `ua` emits "disconnected". `ua` emits disconnected whenever the WebSocket is disconnected. I suspect these Participants lose their WebSocket connection.

| Participant | Disconnect Time | Server-side Reason | ICE Failure? | Notes |
|:--- |:--- |:--- |:--- |:--- |
| PAc8417b538685edd3a25c55aff1c9c2f6 | 2018-08-13T14:30:28.558Z | |
| PA754a03df14c4df53ea5a52a03e91d682 | 2018-08-13T09:06:38.359Z | |
| PAbe6a9007a02e0878fea45c4ede762694 | 2018-08-13T09:17:35.603Z | |
| PA0c2d35dea3003c27eb64cccea5fb0cb7 | 2018-08-13T12:24:44.064Z | | Yes |
| PA760e6412fc42c4b784b568cd1dffd761 | 2018-08-13T12:24:45.126Z | |
| PAb744214127dd4aa194291a87350d1f70 | 2018-08-13T12:50:17.281Z | |
| PA2dd14be8752da7226d6a85b5880b7265 | 2018-08-13T12:58:59.956Z | |
| PA2365202dd4448962acbca21a06964f45 | 2018-08-13T14:10:28.162Z | |
| PAfb85949c98b45ee0355d0d54111edb8b | 2018-08-13T14:16:53.524Z | |
| PAa5dca2a5544c34322a532261bacad161 | 2018-08-13T14:20:25.788Z | |
| PAd0676590677e8ac8937944041442ccc1 | 2018-08-13T14:36:02.910Z | |
| PA82e2375cb4a90babc18bdff2a07a6b29 | 2018-08-13T15:07:44.780Z | |
| PA2735c78508410da3e84c453e74f7cd12 | 2018-08-13T15:08:43.925Z | | Yes |
| PA4fa2003d3d1db9d66c9c0052faf365e2 | 2018-08-13T15:26:20.237Z | |
| PA5bd62b6467f4b39c69fe0d92412db9fe | 2018-08-13T15:53:09.004Z | |
| PAd157fb4f3d144bd8e2685e03de4b1717 | 2018-08-13T16:01:49.199Z | |
| PAae9f52710b11b453f0e8dcc618d70d0f | 2018-08-13T16:01:48.981Z | |
| PAe8abd0e4b9832abadbe09e8382874704 | 2018-08-13T16:15:14.800Z | 53002: Signaling connection timed out (Ping timeout) | Yes | Misses ping by ~28 s |
| PAb9cc5d9b5bc4e892f392f8cb9043e0c8 | 2018-08-13T16:34:09.994Z | |
| PA10ca11a652a51083e9444c3325521c2e | 2018-08-13T17:07:41.618Z | |
| PA7e07e8b7d33d6d1faf9707fbcc04ff28 | 2018-08-13T17:24:00.962Z | |
| PA0dfef004299a57d45eef206a35241ac3 | 2018-08-13T17:24:51.287Z | 53002: Signaling connection timed out (Ping timeout) | Yes | Misses ping by ~28 s |
| PA6cc722eeed252f38c3b3848e6a5ae9c5 | 2018-08-13T17:31:38.330Z | |
| PA4950758018e54a762ba5a5337bb3489f | 2018-08-13T17:44:25.694Z | |
| PA309b754a0472f37ae874e6e445beacd8 | 2018-08-13T18:59:27.830Z | |
| PA42d8109a842597cc270b202b6ae7d4a9 | 2018-08-13T23:24:41.107Z | |
| PA5433fc67c47394811a30ad178dbc94a6 | 2018-08-14T14:24:37.186Z | 53002: Signaling connection timed out (Ping timeout) | | Log is truncated, so I can't see the final disconnect. |

**Comment by sandeepnandula** [comment]
Hi @markandrus,

The same issue what @katranci mentioned above is happening for us also. As you said, the WebSocket is emitting the `Signaling Disconnection` at the same point (e.g.., Websocket error code 1006 and switch cases are fails and going to default error message). Sometimes the `Signaling Disconnection` will happen following by `media connection failure`. We listed few RoomSids below for your debugging purpose:

| RoomSid   | Error triggered |
| ------------- | ------------- |
| RM41b81216c17d0582ef125a156eebb5b0  | Signaling disconnection  |
| RM2e7a08dd26107c0d1251f721321949b7  | Signaling disconnection  |
| RMc55c115bf1f20533ddb4214085e5c335  | (media connection failure and singling disconnection)  |
| RM3bd1611c2fb95a852d8d93639609df84  | (media connection failure and singling disconnection)  |

Please let us know if you like to see the complete logs we will forward you for the above rooms.

**Comment by kamesh-a** [comment]
Hello,

We are getting higher percentage of signalingDisconnectedError, we have our own pings running with WebSocket connected to our server which ping every 60sec and we do have`http` checks as well they are passing.

Please let us know, why these disconnections happened. Are they due to network or due to ping ack failure on sip.

RoomSid | Error triggered
-- | --
RM41b81216c17d0582ef125a156eebb5b0 | Signaling disconnection
RM2e7a08dd26107c0d1251f721321949b7 | Signaling disconnection
RMc55c115bf1f20533ddb4214085e5c335 | (media connection failure and singling disconnection)
RM3bd1611c2fb95a852d8d93639609df84 | (media connection failure and singling disconnection)

**Comment by markandrus** [comment]
Hi @sandeepnandula and @kamesh-a,

I've reviewed your Room SIDs. You can see my notes and additional detail in the table below. Basically, all of these appear to be expected disconnects due to network connectivity issues at the client. A number of the Participants who experienced signaling disconnects first experienced ICE connection failures. These are sort of the "canary in the coal mine" with respect to network issues: you'll typically experience an ICE connection failure first, then a signaling disconnect.

> Websocket error code 1006 and switch cases are fails and going to default error message

The 1006 will be raised by Chrome when the WebSocket connection is closed, but no close frame was received (for example, due to network loss).

> Please let us know, why these disconnections happened. Are they due to network or due to ping ack failure on sip.

Please see below and let me know if you agree with my assessment. If you intend to monitor connectivity yourself, you may want to lower the pings to 15 s or so. ICE failure is typically detected in ~15 s.

I should also mention that some of the work done [here](https://github.com/twilio/twilio-video.js/pull/405) to replace our usage of SIP.js will improve our reconnection story; however, that'll depend on a server deployment that will take some time.

| Room SID | Media Region | Participant Country (approximate) | Participant SID | Disconnect Time | ICE Failure | Server-side Disconnect Reason | Notes |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| RM41b81216c17d0582ef125a156eebb5b0 | in1 | India | PAd35b3263ff33db51bb605db6b0790b3a | 2018-08-22T07:18:47.020Z | | | |
| &hellip; | &hellip; | India | PAf79c814f9e40712f0b670f525cfbce37 | 2018-08-22T07:13:16.640Z | Yes | | We can see from a server-side signaling capture that the client went offline and stopped responding to signaling messages for ~30 s, hence the disconnect. |
| RM2e7a08dd26107c0d1251f721321949b7 | us1 | US | PA3e49d3dd7c30486539f3c302eb59c32b | 2018-08-21T13:32:31.650Z | | 53002: Signaling connection timed out (Ping timeout) |
| RMc55c115bf1f20533ddb4214085e5c335 | us2 | US | PAfe8f7c0caba38d7a720dba572385f5f2 | 2018-08-21T01:00:06.379Z | Yes | 53205: Participant disconnected because of duplicate identity |
| &hellip; | &hellip; | ? | PAcbf6329b0e52fadd6a2a684787b44e45 | 2018-08-21T01:00:07.790Z | | | It looks like, shortly after the first Participant received an ICE failure, you reconnected to the Room with the same identity, hence the 53205. |
| RM3bd1611c2fb95a852d8d93639609df84 | us1 | UK | PAed8a3b69cee341d4acdaeda26ae518b0 * | 2018-08-20T15:24:47.182Z | Yes | 53205: Participant disconnected because of duplicate identity | It looks like, shortly after the first Participant received an ICE failure, you reconnected to the Room with the same identity, hence the 53205. |
| &hellip; | &hellip; | UK | PA31a1d278fb9f95678ccaf2a460fd3d76 * | 2018-08-20T15:31:17.902Z | Yes | |
| &hellip; | &hellip; | UK | PA58442c57a95671639eeb1da5d5e74c61 | 2018-08-20T15:39:05.165Z | Yes | |
| &hellip; | &hellip; | US | PA18c9e4cdf33d1312ef98633faebd9c71 ** | 2018-08-20T15:47:49.899Z | Yes | 53002: Signaling connection timed out (Ping timeout) |
| &hellip; | &hellip; | US | PA328ad0a22245e85ee88b3ad2939368e9 ** | 2018-08-20T15:57:38.315Z | Yes | 53205: Participant disconnected because of duplicate identity | It looks like, shortly after the first Participant received an ICE failure, you reconnected to the Room with the same identity, hence the 53205. |
| &hellip; | &hellip; | US | PA92ece9ca4e901e6e8e3922b18154a130 ** | 2018-08-20T16:08:06.799Z | Yes | 53002: Signaling connection timed out (Ping timeout) |
| &hellip; | &hellip; | US | PA298064925cd42aeb7837674708d5ce9c | 2018-08-20T16:15:46.387Z | Yes | 53002: Signaling connection timed out (Ping timeout) |

\* These Participants share an identity.
\** These Participants share an identity.

**Comment by kamesh-a** [comment]
@markandrus Thanks for those detailed explanations, 

`you'll typically experience an ICE connection failure first, then a signaling disconnect.` - we have found at times, only `SignalingConnectionTimeOut` or `SignalingDisconnectionError` and then followed by receiving a message  `cseq: BYE`  from websocket  or `IceConnectionState`  event opposed to failing with `ice` first.

We have reduced our `ping` checks to `5sec` so in turn to detect are we failing with network? but it looks like in some logs, even a single drop in connection within a `5-10 sec window` coinciding with a `signaling heartBeat` push supposed to be sent, fails and throws us out of the room.

At times, all our pings are passing yet still we are getting `SignalingTimeOut/SignalingDisconnectionError` I can provide few more samples as well. `kedar` also experienced the same issue with one of the calls along with us.

We can send those data along with client logs if you like to take a look.

**Comment by kumail-raza** [comment]
Hi, @manjeshbhargav @markandrus 

Initially the issue from client was reported that the group was perfectly fine, suddenly a new user comes in and everything goes mess, all of them getting drop from the call, after that now client have reported this issue in diff. scenarios. (Note: they all are from US and connected to US media region, with very good internet speed)

Well, we are suggested by support ticket team that we should upgrade our SDK version from 2.0.0 to latest that is 2.5.0, as we find another latest stable release from you guys 2.6.0, we update to it. 

Now we are facing the same issue and on investigating and inspect through logs we find the issue as mentioned above. It is really causing trouble to my client business. We are almost logging Twilio feature when we are calling any of your APIs, and when your SDK or StatusCallBack response. We are also enable NetworkQualityCheck on LocalParticipant, we do get (bad and very bad network alerts), but as mentioned earlier user are having with very good internet connection. 

My client is actually doing demo with his client and while doing demo it happens and its now 6th and 7th incident, which really embarrassing and client start losing his customers. 

What I want to know here first, where we are missing or doing mistake in investigating the root cause of the issue, any direction from you guys will be appreciated.

RoomSID of the call the client had yesterday is : **RM9dd6c44bbd5a4a8857748de90b15b840**

**ImpNote:** One more thing our client observe the issue in two of the conversation, and they observe one pattern that is after 40minutes of the conversation in both the conversation they had a issue with almost half or all of the users.
