### ISSUE TITLE
Twilio Track Subscription API Issue

### ISSUE THREAD

**Issue by Jaikishann** [twilio/twilio-video.js#403]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

### Apis used:
-Subscribing or Unsubscribing Using TrackSid Only 
-Subscribing or Unsubscribing Using Track Name and ParticipantSid 

</br>

### Subscribing or Unsubscribing Using TrackSid Only:

**Expected behavior:**
The track which is already unsubscribed should remain unsubscribed when a new track is 
unsubscribed
**Using this request URL (POST):**
```https://video.twilio.com/v1/Rooms/RM2850c27e14a5dc22007dbaaac2d2ab1c/Participants/bc645857-9fb8-11e8-9eb2-3b2bb96560ea/SubscribedTracks```
**Payload:**
```Track=MT7b133d315a57746bbe3e3eb40cdb7a2c&Status=subscribe```

**Actual behavior:**
As soon as the second track is unsubscribed, the first track is subscribed automatically back again.

</br>

### Subscribing or Unsubscribing Using Track Name and ParticipantSid:

**Expected behavior:**
Only the track of requested participantSId should be unsubscribed.
**Using this request URL (POST):** ```https://video.twilio.com/v1/Rooms/RM2850c27e14a5dc22007dbaaac2d2ab1c/Participants/bc645857-9fb8-11e8-9eb2-3b2bb96560ea/SubscribedTracks```
**payload:** ```Track=camera&Status=unsubscribe&Participant=PA0acae47cd13aab68bad83b4f6c0c5b5b```

**Actual behavior:**
Tracks of all the participants in the current call are getting unsubscribed.

**Software versions:**

 - [x] Browser(s): Chrome
 - [x] Operating System: Mac OS
 - [x] twilio-video.js: 1.13.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): React

**Comment by innerverse** [comment]
Hi @Jaikishann -

First of all, thank you for participating in our Early Access for the Subscriptions API!  What you're seeing is expected behavior with the current design:

1. Only one subscription filter can be applied at a time - the subscription changes are "atomic" and override previous filters
2. Only one subscription filter can be sent at a time
3. The subscription filter is only applied once

We realize the limitations 2 & 3 and will be adding additional features to address these limitations before Public Beta.  

For now, let's keep this ticket open to track the current status of the Early Access Subscriptions API.

Thanks again - more soon!
-Seth
