### ISSUE TITLE
Cordova support

### ISSUE THREAD

**Issue by sagivf** [twilio/twilio-video.js#404]
Hey all,

I created a repo for implementing the https://github.com/twilio/video-quickstart-js
example in an Ionic3 app - https://github.com/sagivf/twilio-video-ionic.

It works nicely on android and although I thought it would work on IOS11 it doesn't... :(
Am I correct to assume this is unsolvable without a cordova plugin?

The cordova plugin I've seen in the issues doesn't really seem usable:
https://github.com/twilio/twilio-video.js/issues/85
https://github.com/PriceFallin/cordova-plugin-twilio-video

I really want to use twilio video in my cordova app, any ideas?

**Comment by markandrus** [comment]
Hi @sagivf,

My guess is that Android works because Cordova runs in a WebView that provides WebRTC APIs needed by twilio-video.js. For iOS, I think the UIWebView does not allow access to these APIs—only Safari has access to them. I'm not sure when Apple will make those APIs available to lower levels like UIWebView.

Unfortunately, we are not providing Cordova support at this time, but I do know the cordova-plugin-twilio-video project has worked for some customers. We are currently working on a React Native SDK. Once that's out, we may reconsider Cordova.

Best,
Mark

**Comment by joelgetaction** [comment]
Hi @markandrus - you mentioned

> Hi @sagivf,
> 
> My guess is that Android works because Cordova runs in a WebView that provides WebRTC APIs needed by twilio-video.js. For iOS, I think the UIWebView does not allow access to these APIs—only Safari has access to them. I'm not sure when Apple will make those APIs available to lower levels like UIWebView.
> 
> Unfortunately, we are not providing Cordova support at this time, but I do know the cordova-plugin-twilio-video project has worked for some customers. We are currently working on a React Native SDK. Once that's out, we may reconsider Cordova.
> 
> Best,
> Mark

Hi,

Thanks @markandrus .  Is your ReactNative SDK available yet and can we get early access to it if not?  We are eager to use and pay for Twilio video on React Native.

Thanks!

**Comment by JamieCorkhill** [comment]
@markandrus, @manjeshbhargav was providing access to the SDK in #510. Do you know if/when the SDK will be released or has it been abandoned since there have been no updates?

Thanks.

**Comment by msd117** [comment]
Any update on the Cordova support @markandrus
