### ISSUE TITLE
User has disconnected from Twilio room unexpectedly: Signaling connection disconnected

### ISSUE THREAD

**Issue by jamesgraham** [twilio/twilio-video.js#416]
We are seeing quite a few of these, are they normal?

Room: RMfed8889f26c93c4b89968ffde61c1c70
Participant: PAf42c3e2f30cbaa04939d2283a6e14871

![image](https://user-images.githubusercontent.com/934542/45360317-d9b64f80-b5d7-11e8-9b65-85e5107c4f66.png)

Checking a few of these, they appear to be during a page refresh.

**Comment by manjeshbhargav** [comment]
Hi @jamesgraham ,

Sorry for the delayed response. When you refresh the page, and you don't call `room.disconnect()` on page unload, the signaling connection is abruptly terminated.

It is all the more important that you disconnect from the Room on page unload when you have opted in for the Reconnection feature in [twilio-video.js@2.0.0-beta6](https://github.com/twilio/twilio-video.js/blob/2.0.0-beta6/CHANGELOG.md) because if you don't disconnect, Twilio will wait for about 30-45 seconds for the Participant to reconnect before notifying others that he/she left the Room.

Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team
