### ISSUE TITLE
participant.networkQualityLevel returns null

### ISSUE THREAD

**Issue by lightbringer2994** [twilio/twilio-video.js#519]
console.log(participant.networkQualityLevel) seems to return null.
Type of room: Group
 - [x] Browser(s): Chrome 71
 - [x] Operating System: Ubuntu 16.04
 - [x] twilio-video.js: 2.0.0-beta5
 - [x] Third-party libraries: React

**Comment by manjeshbhargav** [comment]
Hi @lightbringer2994 ,

Thanks for writing in with your issue. I have a couple of questions:

1. Have you enabled the Network Quality API with
```js
connect(token, { networkQuality: true });
```

2. Right now, Network Quality is reported only for the LocalParticipant. So, are you trying to log `networkQualityLevel` on the LocalParticipant or on the RemoteParticipant?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by lightbringer2994** [comment]
1) Yes.
2) I am trying to log the networkQualityLevel for the localParticipant.

When I log the localParticipant as a whole, it does conatin networkQualityLevel.

**Comment by manjeshbhargav** [comment]
@lightbringer2994 ,

Can you consistently reproduce this behavior (Logging the level returns null for network quality, but logging the LocalParticipant as a whole has a valid network quality score)? Can you log both and then send me a snapshot of the console logs?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by babubalakrishnan** [comment]
Hi @manjeshbhargav 
I am facing the same issue for local participant, able to see networkQualityLevel value in the web console, when I am accessing networkQualityLevel from same object through console log is returning null

returning null in console.log
![twilio-video-session-console-log](https://user-images.githubusercontent.com/18712986/52632697-45367d00-2ee8-11e9-9186-f70f70568f3a.png)

able to see it in web console
![twilio-video-session-web-console](https://user-images.githubusercontent.com/18712986/52632698-45cf1380-2ee8-11e9-9fd1-051943643f56.png)

 networkQualityLevel returns null.

**Comment by viktorhunko** [comment]
Hi, @manjeshbhargav 
I am facing almost same issue, in my case even logging the LocalParticipant as a whole has `networkQualityLevel: null`.
And `networkQuality` is set to true in options while connecting.
twilio-video: 2.0.0-beta4
Chrime: 72

**Comment by lrickeypmd** [comment]
Hello @manjeshbhargav 

Are there been any updates on this issue? I am still receiving `networkQualityLevel: null` for the LocalParticipant and all RemoteParticipants.
I have added `networkQuality: true` to my options while connecting.
I have tested it on 2.0.0-beta5 and 2.0.0-beta6. 
I am using Chrome: 72 on macOS version 10.14.3.

**Comment by manjeshbhargav** [comment]
Hi @lrickeypmd ,

Are you publishing any Tracks when you join the Room? Also, can you give me some Room SIDs so that I can take a look at the logs to see if anything is amiss?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by lrickeypmd** [comment]
@manjeshbhargav 

I am publishing tracks when I join the room using:
`Video.connect(token, {
    name: roomName,
    tracks: localTracks,
    networkQuality: true
  })`
where `localTracks` are the tracks received from:
`Video.createLocalTracks({
		audio: true,
		video: true
	})`
Here is the room SID from a recent call where I confirmed I am receiving `networkQualityLevel: null` through the console for the LocalParticipant and the RemoteParticipant: `RMbfecf51b16ce73644a94d32e92d4402f`
My other calls would all be very similar to this one. Please let me know if there is any additional information you would like or if there is something specific you would like me to test.

**Comment by manjeshbhargav** [comment]
Hi @lrickeypmd ,

The Room logs indicate that it is a peer-to-peer. The Network Quality API [is only available in group or small group Rooms](https://www.twilio.com/docs/video/using-network-quality-api#using-the-network-quality-api). Please try joining a group Room and see if it works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by lrickeypmd** [comment]
Hi @manjeshbhargav ,

Thank you for your help! Are there any alternatives you can suggest for users using peer-to-peer connections? I am attempting manage end-users connection quality and/or prioritize audio over video if their connection is poor.

**Comment by manjeshbhargav** [comment]
Hi @lrickeypmd ,

You can come up with your own network quality metrics using the [Room.getStats](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta7/docs/Room.html#getStats__anchor) API. Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by lrickeypmd** [comment]
Hi @manjeshbhargav ,

Thank you for that suggestion! This looks like the Room.getStats API will be able accomplish what I am looking for. However, I ran into 2 browser-specific issues.

1. On Chrome 27: I am getting: `frameRate: null
packetsLost: null
roundTripTime: null` for  local tracks and `frameRate: null` on remote tracks. This makes it difficult on Chrome to determine if just my connection is poor. An example of a room SID where I experienced this issue is `RM44ddb1a310e67cc78b14daa605fc1f89`

2. I am running Safari 12.0.3 and I am receiving an error saying: `Unhandled Promise Rejection: Error: getStats() is not supported on this version of Safari due to this bug: https://bugs.webkit.org/show_bug.cgi?id=192601` indicating the Room.getStats API is not currently supported on the newest version of Safari.

**Comment by lrickeypmd** [comment]
Hi @manjeshbhargav ,

Do you have any updates on these issues? The most important fix for me would be to receive `roundTripTime` info on Chrome. It is an import tool to infer the network's latency.

**Comment by manjeshbhargav** [comment]
Hi @lrickeypmd ,

Sorry for the delayed response. The stats which are `null` are usually so because the browser hasn't implemented/exposed these WebRTC standard stats yet. We also do not support `Room.getStats()` on Safari yet due to the bug specified in the error message.

Regarding your particular use-case, we are working on providing an API in Group Rooms which you can use to prioritize certain Tracks over others. Our media server will then automatically degrade/switch off lower priority Tracks based on its assessment of a particular peer's bandwidth. We are aiming to release this at the end of Q2, 2019.

In the meantime, please consider using small group Rooms so that you can enable the Network Quality API. You can couple this with `LocalParticipant.setParameters()` to control the send bandwidth of audio/video Tracks.

Please let me know if this works for you.

Thanks,

Manjesh Malavalli

**Comment by lrickeypmd** [comment]
Hi @manjeshbhargav ,

My group wants to only use peer-to-peer rooms. Can you answer a quick question for me? In version 2.0.0-beta7 the room stats gathered by `chromeOrSafariGetTrackStats` are null if retuned by `standardizeChromeOrSafariStats` but not null if returned by `standardizeChromeLegacyStats`. However, mine are null on chrome version 73 because `standardizeChromeLegacyStats` is only used if `chromeMajorVersion && chromeMajorVersion < 67`. Why was this version check added? It appears that removing it would solve my problem on chrome version 73.

**Comment by manjeshbhargav** [comment]
@lrickeypmd ,

We stopped using Chrome's legacy `getStats` implementation for 2 reasons:

1. It breaks when Chrome sets "unified plan" as the default SDP format.
2. Chrome is removing this implementation starting from M75.

However, the `roundTripTime` information is available in the RTCIceCandidate pair stats, which is not exposed through the `Room.getStats()` API yet. You can access it as follows:

```js
const peerConnections = [...room._signaling._peerConnectionManager._peerConnections.values()]
  .map(pcSignaling => pcSignaling._peerConnection);

const statsList = await Promise.all(peerConnections.map(pc => pc.getStats()));

const iceCandidatePairStats = statsList.map(stats =>
  [...stats.values()].find(stat => stat.type === 'candidate-pair'));

iceCandidatePairStats.forEach(stat =>
  console.log(stat.currentRoundTripTime, stat.totalRoundTripTime));
```

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team
