### ISSUE TITLE
Error in getstats module when checking for Chrome browser.

### ISSUE THREAD

**Issue by srobertson421** [twilio/twilio-video.js#529]
- [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [x] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

```js
import { connect } from 'twilio-video';
```

**Expected behavior:**

Expect no errors to occur in module import

**Actual behavior:**

Library produces error when running Chrome browser in mobile browser mode via Devtools. UserAgent string isn't matching via `getStats.js` module and returns a null. Then when that returned value index `[1]` is checked for, it errors out.

![twilio-video-err](https://user-images.githubusercontent.com/2695134/52316380-eca73300-296f-11e9-9471-217d31e30093.PNG)

**Software versions:**

 - [x] Browser(s): Chrome 72
 - [x] Operating System: Windows 10
 - [x] twilio-video.js: 1.15.1
 - [x] Third-party libraries (e.g., Angular, React, etc.): Vue

**Comment by manjeshbhargav** [comment]
@srobertson421 ,

Thanks for writing in with your issue. The reason this is happening is because in mobile mode, Chrome still has the global `webkitRTCPeerConnection` defined, which we use to determine that the current browser is Chrome. But the `userAgent` has changed to Safari.

In 1.16.0 (and 2.0.0-beta6), this will be fixed by depending on `userAgent` to determine the browser instead of the prefixed PeerConnection object. We will reach out to you once this is available.

Thanks,

Manjesh Malavalli
JSDK Team
