### ISSUE TITLE
Publishing local tracks from Chrome screen share

### ISSUE THREAD

**Issue by gytdau** [twilio/twilio-video.js#571]
Hey,
I've run into a wall trying to implement Chrome's screensharing without an extension.

```js
    navigator.mediaDevices.getDisplayMedia().then(stream => {
      return Video.createLocalVideoTrack({
        video: {
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: stream.id
          }
        }
      })
    }).then((localVideoTrack) => {
      let localParticipant = this.state.participants[this.identities.local]
      const tracks = Array.from(localParticipant.videoTracks.values());
      localParticipant.unpublishTracks(tracks);

      localParticipant.publishTrack(localVideoTrack)
    })
```

The particular problem is that the video track returned by `Video.createLocalVideoTrack` isn't the video track of the stream, but instead the user's camera video stream. This code just appears to unpublish the current camera video stream, and then publish it back again. I feel there's something obvious I'm missing here, but can't pinpoint what.

Could you guys share some insight into why this is happening?

**Comment by manjeshbhargav** [comment]
Hi @gytdau ,

Thanks for writing in with your question. `getDisplayMedia()` resolves the returned Promise with a MediaStream containing the desktop screen's MediaStreamTrack. You can use it to create a [LocalVideoTrack](https://media.twiliocdn.com/sdk/js/video/releases/2.0.0-beta5/docs/LocalVideoTrack.html) as follows:
```js
navigator.mediaDevices.getDisplayMedia().then(stream => {
  const screenTrack = stream.getVideoTracks()[0];
  return new Twilio.Video.LocalVideoTrack(screenTrack);
});
```
Please let me know if this works for you. Since I've answered your question, I will close this issue for now.

Thanks,

Manjesh Malavalli
JSDK Team
