### ISSUE TITLE
dominantSpeaker feature for local identity?

### ISSUE THREAD

**Issue by devinterx** [twilio/twilio-video.js#604]
**dominantSpeakerChanged** return only remote participants? how to detect when i'am speaking?

**Software versions:**

 - [ ] Browser(s): Chrome 73, Vivaldi
 - [ ] Operating System: Windows 7
 - [ ] twilio-video.js: 1.14.2
 - [ ] React

**Comment by manjeshbhargav** [comment]
Hi @devinterx ,

Thanks for writing in with your question. In our current implementation of the Dominant Speaker API, you will not receive a "dominantSpeakerChanged" event if the LocalParticipant is the dominant speaker. However, you can achieve this by having one of the other Participants send you an out-of-band message if they detect that you are the dominant speaker.

Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by p8952** [comment]
@manjeshbhargav Sorry to open an open issue.

Having one of the other Participants send you an out-of-band message if they detect that you are the dominant speaker doesn't seem to work, the way dominant speaker seems to be working is that it's raised when the dominant speaker among the RemoteParticipants changes.

So if a Room has two Participants, A and B:

A will receive a "dominantSpeakerChanged" event saying B is the dominant speaker
B will also receive a "dominantSpeakerChanged" event saying A is the dominant speaker.

Do you have any advice for how best to implement a system where the person currently speaking is highlighted, even if that person is yourself?

**Comment by manjeshbhargav** [comment]
Hi @p8952 ,

When I was talking about Participants sending an out-of-band message to their Dominant Speaker, I meant that this has to be implemented by the application since this behavior does not exist in the SDK. You can do this by sending a message to the Participant over a DataTrack. If a Participant receives a message from everybody else, then that Participant is the dominant speaker. Hope this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by melissadu** [comment]
Hi @manjeshbhargav, 

This suggestion doesn't work for the two person case, as @p8952 pointed out above. When there are just 2 people in a group room, participant A will think participant B is the dominant speaker, and participant B will think participant A is the dominant speaker. And because there are just 2 people in the room (one Remote and one Local), the dominantSpeaker event will never get triggered.

Do you have suggestions for how to detect the active speaker in the two person case? Your suggestion works great for the 3+ person case.

Thanks in advance.

**Comment by amitava82** [comment]
Not sure why this issue is closed. This is still am issue. Is there any solution for this particular problem?
