### ISSUE TITLE
twilio video call not working in chrome latest version

### ISSUE THREAD

**Issue by phplead** [twilio/twilio-video.js#611]
hi, I am not able to connect the Twilio video calling in chrome latest version. I have updated the node version with 6.11.0 and npm version 3.10.10. I have also updated the Twilio version with 3.30.1. please suggest me something.

Thank You

**Comment by manjeshbhargav** [comment]
Hi @phplead ,

Please provide the following information so that we can get some context about the issues that you are facing:

 - [ ] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Code to reproduce the issue:**

A JSFiddle, CodePen, Plunker, or Gist is great, too!

```js
// TODO
```

**Expected behavior:**

TODO

**Actual behavior:**

TODO

If possible, please include debug logs. You can set the log level for
twilio-video.js by calling `connect` with the `logLevel` property, e.g.

```js
connect(token, { logLevel: 'debug' })
```

Then you can copy and paste or save the logs from your browser's console.

**Software versions:**

 - [ ] Browser(s):
 - [ ] Operating System:
 - [ ] twilio-video.js:
 - [ ] Third-party libraries (e.g., Angular, React, etc.):

Thanks,

Manjesh Malavalli
JSDK Team
