### ISSUE TITLE
Networkquality level availible for remote?

### ISSUE THREAD

**Issue by kmahlqvist** [twilio/twilio-video.js#623]
Hi, I'm using 1.16.0 with small group rooms. And to my understanding network quality levels should be emitted for remote participants now?
I'm sending the following with my connectOptions
```
{
dominantSpeaker: true,
networkQuality: true,
}
```
And dominantSpeaker works fine. But not getting anything from subscribing to participant.on('networkQualityLevelChanged).

Am I missing something?

**Comment by manjeshbhargav** [comment]
Hi @kmahlqvist ,

We support Network Quality reports for RemoteParticipants starting from 1.18.0. Please take a look at the [CHANGELOG](https://github.com/twilio/twilio-video.js/blob/1.18.0/CHANGELOG.md) for how to enable this feature.

I will close this issue since upgrading to 1.18.0 should work. Please feel free to open a different issue if you run into any specific problems with it.

Thanks,

Manjesh Malavalli
JSDK Team
