### ISSUE TITLE
Twilio Video performance bench-marking with atmost 50 participant in a group?

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#626]
Any bench-marking tools or strategies to test 25+ or at most 50 participant in a group room with twilio-video program?

- We need to check the Twilio itself performance impact.
- We need to check what will be the performance at the client side app on their PC when their browser listening so many streams and rendering them.

**Comment by smkrn110** [comment]
Hi @anna-vasilko

**Comment by anna-vasilko** [comment]
Hi @smkrn110 
Great question, not too many tools our there allow this kind of testing. 
We have internal tools for it and tried few third party ones. You could use either https://loadero.com/ or https://testrtc.com/. Both of them allow to configure tests such that you have many clients joining same video room. Both tools provide webrtc stats and some hardware metrics after the test.

Things to consider:
- Normally you start hitting client-side limits when too many participants share tracks in a big room. Room maximum is 50 participants and our backend supports the case of everyone sharing and receiving. But users normally can't handle too many incoming streams because of network or hardware reasons. 
- Those limits heavily depend on specifics of your use case - how many participants share tracks, what kind of tracks, what video resolution etc. Plus specifics of hardware and networks used by clients.

If you can describe your use case, we would be happy to think of and suggest how to achieve optimal performance for your case with our SDK.

**Comment by smkrn110** [comment]
Hi @anna-vasilko 

The things to consider you have mentioned was the first came into my mind, but Is there a way to stream (via typical streaming channels/scalable to millions) a view or composite of a room?

**Comment by smkrn110** [comment]
@anna-vasilko any update?

**Comment by manjeshbhargav** [comment]
Hi @smkrn110 ,

You would have to build a service which subscribes to the Tracks in a Twilio Room and build a composite HLS stream. There are some out-of-the-box solutions available, but I don't have enough information about them.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by smkrn110** [comment]
Ok closing this issue will continue if further assistance require on this. Thanks

**Comment by evolross** [comment]
Anyone know a WebRTC service that can support up to the 1000 that WebRTC is supposed to be able to achieve?

**Comment by francescov1** [comment]
@evolross We've used Tokbox/Vonage in the past. It's quite solid, although their SDKs, docs, and overall dev experience is not as nice as Twilio (hard to beat). 

It allows up to 3000 streams (twilio track equivalent). If you only have one publisher, this allows up to 3000 viewers. As you increase publishers, number of viewers decreases though - https://support.tokbox.com/hc/en-us/articles/360029732691-How-do-I-estimate-my-OpenTok-monthly-usage-

Also note that we found their service widly more expensive for group calls (everyone streaming video) because of their pricing structure (sometimes even 10x or 20x more expensive per 1-2hr call) but 1-many tend to be cheaper than twilio.
