### ISSUE TITLE
Screen Capture not displaying if other video track is removed

### ISSUE THREAD

**Issue by Samenai** [twilio/twilio-video.js#63]
Hi All!

My team over here has been working to integrate Twilio Video (1.0.0-beta4) into our tool and we've run into a hiccup.  We have a working extension on the Chrome Webstore and we are successfully handling screen capture locally but unfortunately we cannot get it to display on remote participants, unless remote participants are joining after a user is already sharing their screen.

Workflow is as follows:
User clicks on Desktop Share icon and extension is either inline installed or run to request what the user would like to share.  After sharing, we remove their camera using removeCamera() on localParticipant and then add their screen capture stream to localMedia using addStream(stream) and attach it to various elements on the html.

Meanwhile, remote participants get both trackRemoved and trackAdded events and create a 'participant' div and attach any media that might be present.

The issue we are having is that our code to attach video and audio tracks to elements are working for both video camera and screen capture tracks but our site is not displaying the screen capture track.  We can see that the div has a `<video>` tag for the screen capture track but it isn't displaying anything.  

Tricky thing is, if a new user joins the video chat, the process to attach the track is the exact same, but they can see the screen capture stream perfectly. That is until the screen sharer decides to turn off and then back on their screen capture and it's gone again.

Any thoughts? Thanks for your help. Willing to post code as needed.

Edit: Additionally, it doesn't appear that trackRemoved or trackDisabled event is triggered when a user hits the 'Stop sharing' button on the bottom of their screen during screen capture.

**Comment by Samenai** [comment]
In regards to the above Edit section, I solved this using

`stream.getVideoTracks()[0].onended = function () {
 
 };`

**Comment by Samenai** [comment]
I believe I've fixed the issue (just need to handle the enable/disable of the tracks better now, but others can see the screen share track now) by utilizing a different method to add the track as opposed to what's shown in the [documentation](https://www.twilio.com/docs/api/video/screen-capture-chrome?code-sample=code-getuserscreen-implementation&code-language=js&code-sdk-version=default). (The difference being navigator.mediaDevices.getUserMedia to Twilio.Video.getUserMedia, this.localMedia.addCamera(constraints) also works)  See below:
```
return new Promise((resolve, reject) => {
  chrome.runtime.sendMessage(<chrome-extension-id>, {
    type: 'getUserScreen',
    sources: ['window', 'screen', 'tab']
  }, (response) => {
    switch (response && response.type) {
      case 'success':
        resolve(response.streamId);
        break;
      case 'error':
        reject(new Error(error.message));
        break;
      default:
        reject(new Error('Unknown response'));
        break;
    }
  });
}).then(streamId => {
  Twilio.Video.getUserMedia({
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        maxWidth: 1920,
        maxHeight: 1080,
        maxFrameRate: 24,
        minAspectRatio: 1.77,
        chromeMediaSourceId: streamId
      }
    }
  }).then((mediaStream) => {
    if (mediaStream) {
      this.desktopShareStream = mediaStream;
      this.localMedia.addStream(mediaStream);
      this.desktopShareStream.getVideoTracks()[0].onended = function () {};
    }
  });
}).catch((e) => {
  console.log(e);
});
```

**Comment by markandrus** [comment]
Hi @Samenai,

I'm glad you were able to work through it—I just wanted to circle back on some of the items you raised:

> we cannot get it to display on remote participants, unless remote participants are joining after a user is already sharing their screen.

Interesting... I am wondering if you have listeners for "trackAdded", etc.? The code ought to attach any `tracks` already present on a Participant and also subscribe to "trackAdded" events. FWIW, we have an internal dog food app supporting screen share, and have not run into this issue.

> Edit: Additionally, it doesn't appear that trackRemoved or trackDisabled event is triggered when a user hits the 'Stop sharing' button on the bottom of their screen during screen capture.

Yes, this is indeed an issue when a user stops sharing: the underlying MediaStreamTrack goes to `readyState` "ended", although we do not update the `isEnabled` state or fire a "trackDisabled" event (since that property is independent) nor do we automatically remove ended Tracks. We are adding a "trackStopped" event and `isStopped` property in the next 1.0.0-beta5 release to address this.

> The screen sharing track only works if:
>
> 1. It's the only video track the participant has. AKA the participant does not have a camera (and it works when removing and adding the track again)

This is also strange... FWIW, our dog food app using these APIs can send both the webcam and screen share.

> dealing with the two tracks (differentiating between them for enabling/disabling) has proven difficult

Yes, this is a real pain point :-( we plan on introducing Track names—specifically a Track `name` property—to allow distinguishing, e.g., screen share from webcam and vice versa.

I'm sorry you've had some trouble! Your feedback is valuable though, and we plan on addressing some of these pain points soon.

Best,
Mark
