### ISSUE TITLE
Signaling connection disconnected and sip.transport

### ISSUE THREAD

**Issue by pixsolution** [twilio/twilio-video.js#635]
Hello! We are working with Twilio in Laravel where we have implemented a programmable video, and when making the Video call to enter the video room, the camera is not ON and immediately I get these errors: Could not connect to Twilio: Signaling connection disconnected and sip.transport | WebSocket abrupt disconnection. I attached a screen shot of this error https://ibb.co/0QwFKwL

How can I solve this error?
I have read that we must update the sdk by referring to it by cdn https://media.twiliocdn.com/sdk/js/client/v1.7/twilio.min.js
but referencing it in direct script displays the same error, how can we solve it?

Moreover, we have installed sdk through composer "twilio / sdk": "^ 5.31",

and by cdn referral we have this
<script src = "https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"> </ script>
<script src = "https://media.twiliocdn.com/sdk/js/conversations/v0.13/twilio-conversations.min.js"> </ script>
<script src = "https://cdn.firebase.com/js/client/2.4.0/firebase.js"> </ script>
with which our videochat worked and in previous versions of browsers. It works in chrome versions 72 and below and it doesn´t work in the new Chrome 74 version. In Opera Version: 58.0.3135.132 it works

I will appreciate your help
Thanks
Regards

**Comment by manjeshbhargav** [comment]
Hi @pixsolution ,

Thanks for writing in with your question.

> I have read that we must update the sdk by referring to it by cdn https://media.twiliocdn.com/sdk/js/client/v1.7/twilio.min.js
but referencing it in direct script displays the same error, how can we solve it?

This URL loads the Voice SDK, not the Video SDK.

> Moreover, we have installed sdk through composer "twilio / sdk": "^ 5.31",
and by cdn referral we have this <script src = "https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"> <script src = "https://media.twiliocdn.com/sdk/js/conversations/v0.13/twilio-conversations.min.js"> <script src = "https://cdn.firebase.com/js/client/2.4.0/firebase.js"> with which our videochat worked and in previous versions of browsers.

`twilio-common.js` and `twilio-conversations.js` are really old versions which we no longer support. Also, Chrome 72 switched made a breaking change in its WebRTC implementation. In order to work around it, please upgrade your Video SDK dependecies to the versions mentioned in [this advisory](https://support.twilio.com/hc/en-us/articles/360012782494-Breaking-Changes-in-Twilio-Video-JavaScript-SDKs-December-2018-), which we published in December 2018.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by pixsolution** [comment]
Hello @manjeshbhargav 
Thanks for your reply!

When you mention that twilio-common.js and twilio-conversations.js they're really old versions that no longer support and you recommend that update the dependencies of Video SDK to versions 1.14 or 1.18 is there any way to do it through composer? Could you give me an example? I'm new to this, because my application does not use npm precisely to install those dependencies ... and referencing by cdn placing the script in the view <script src="https://media.twiliocdn.com/sdk/js/video/releases/1.14.1/twilio-video.min.js" ></script> 
even so it keeps coming out > Could not connect to Twilio: Signaling connection disconnected

Hope you can help me
Regards

**Comment by manjeshbhargav** [comment]
Hi @pixsolution ,

Composer loads Twilio's PHP helper library for using our REST API for creating and managing Rooms as well as vending AccessTokens. This is different from twilio-video.js, which is our client-side library. It  should work when you add it using the CDN link in a <script> tag.

Can you share your browser console logs with me?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by pixsolution** [comment]
Hello @manjeshbhargav 

Thanks for your reply

Of course, yes you can see the screenshots here after applying the CDN link in the <script> tag:

![image (19)](https://user-images.githubusercontent.com/47191848/57556227-bb773e00-7376-11e9-9e81-b3e0a49ef9a1.png)
![image (20)](https://user-images.githubusercontent.com/47191848/57556247-c5993c80-7376-11e9-9441-951adfe658e8.png)
![image (21)](https://user-images.githubusercontent.com/47191848/57556266-d21d9500-7376-11e9-9069-4db454fd8358.png)
![image (22)](https://user-images.githubusercontent.com/47191848/57556283-e19cde00-7376-11e9-99a3-740a0431cb12.png)
![image (23)](https://user-images.githubusercontent.com/47191848/57556318-fda07f80-7376-11e9-9560-da17fe5dd703.png)

The same thing happens in localhost 127.0.0.1:8000 than in production on the server

Regards

**Comment by pixsolution** [comment]
Hello @manjeshbhargav 

Hope you're doing well!

Do you have any answer please? from my last reply

Thanks
Regards

**Comment by manjeshbhargav** [comment]
Hi @pixsolution ,

I took a look at the Room logs, and for some reason the SDPs generated by the client is in `unified-plan` format, while the client is registering itself with Twilio as a `plan-b` client. These are two different SDP formats. That is the reason the logs show a `Client is unable to apply a remote description` error message. Can you share with me the `ConnectOptions` object that you use to join a Room?

Also, is it possible for me to get access to your application so that I can do some console debugging to see what might be causing this SDP format mismatch?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by pixsolution** [comment]
Hello @manjeshbhargav 

Thanks for your reply

Do you mean this?
![image (24)](https://user-images.githubusercontent.com/47191848/57679257-26509f80-762b-11e9-91b1-7f6a591bf99b.png)
I share the file where is that code of the capture and almost all the code of the video call:
[video-app-new.zip](https://github.com/twilio/twilio-video.js/files/3176350/video-app-new.zip)

What is the access to the app you refer to an online link where you can try the video call? ok later I enable the video call button on my website again that disables it for users because it did not work and I share a username and password so you can try

Regards

**Comment by pixsolution** [comment]
Hi @manjeshbhargav 

Here you can test the videocall on browser:

Link for start a videocall: https://www.saludvitale.com/panama/virtualquery/295 choose the left plan "Consulta Express"

Yo have to login as a Patient user for start the videocall:
email: usuario@mail.com
pass: eload12345

and in the other side you need to have logged in as a Doctor user:
email: pix.appmovil@gmail.com
pass: eload12345

[VideoChat-files.zip](https://github.com/twilio/twilio-video.js/files/3177692/VideoChat-files.zip)
I forgot to send you in the previous message the controller that also handles a lot of not saying all of the video call, if you want to see part of the functions where createChannel channel is created that I think was something you asked us, right?

I appreciate your help
Thank you
Regards
