### ISSUE TITLE
Network Quality API not working as expected.

### ISSUE THREAD

**Issue by EmilNordling** [twilio/twilio-video.js#640]
Hi! 👋

This is more a feature request than a bug report (I think). In 1.18.0 the [Network Quality API](https://www.twilio.com/docs/video/using-network-quality-api) finally got available, we've been waiting for this feature come inorder to have a reliable way of checking connectivity issues of the other participants. It existed an assumption that level 0 would be emitted if that participant would stop sending data / lose connection - this never happened, reading from the docs it looks like it should: 
>For this, the Network Quality API uses an algorithm that ingests both Client and Server metrics and computes a Network Quality Level on the following Likert scale:

And for level 0 it states that it'll be emitted when:
>Network broken (reconnecting)

On the other hand the docs also states that:
>... Note that while a Room is in the reconnecting state, a LocalParticipant's Network Quality Level is set to 0.

Does this mean the level 0 is only tied to room and not individual participants? If so, it seems flawed and is not lining up with what the docs is primary stating: that the level is tied to the participant.

And if it is only tied to the participant, when is level 0 supposed to be emitted?

If it's working as intended from your end, we would like to make the feature request to send out level 0 if a remote participant is no longer sending data when he/she should. 😄

---

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**Expected behavior:**
When a participant stop sending data and the Network Quality  API recognizes it, the other participants should receive an `networkQualityLevelChanged` event with `networkQualityLevel` being 0.  

**Actual behavior:**
No `networkQualityLevelChanged` event is being sent out for the other participants if I were to disconnect my internet and stop sending data.

**Software versions:**

 - [x] Browser(s): Chrome 74.0.3729.108
 - [x] Operating System: macOS Mojave 10.14.4
 - [x] twilio-video.js: 1.18.0
 - [ ] Third-party libraries (e.g., Angular, React, etc.): not applicable for this issue.

**Comment by smkrn110** [comment]
@manjeshbhargav 

This is something really a concern as we are facing very bad and bad network status consistently even with very high bandwidth internet 19Mb to 25Mb. Users are in the U.S and the region is also explicitly set with the U.S.

**Room SID:** RM0416cbf46f981f414f26b5c2a2e00676

**Comment by ceaglest** [comment]
Hi,

> This is something really a concern as we are facing very bad and bad network status consistently even with very high bandwidth internet 19Mb to 25Mb. Users are in the U.S and the region is also explicitly set with the U.S.

I just wanted to offer one small piece of information, before other team members  respond. 

In a Group Room without simulcast, the quality of the Participants published video is limited by the requirements and capabilities of each subscriber. Simulcast is one area that could potentially improve quality (allow better send network scores for Participants, who aren't able to use all of their bandwidth). When I looked at the Room SID, there was a long period (after everyone had joined) where some Participants had low estimated send bandwidth, and also low network scores because of that. Getting to the root cause of why the available bandwidth is low, given the Participant's fast connections and proximity to us1 is something I might need help with from other team mates.

I also noticed that muting is used for long periods (often minutes) by Participants. I would suggest that it might be a worthwhile optimization to unpublish Participant audio if it all that is being sent is silence (at ~20 kbps per Participant). This will lower the bandwidth floor, and save more Room for video Tracks. @manjeshbhargav do you concur, would this make sense?

Best,
Chris

**Comment by smkrn110** [comment]
@manjeshbhargav @ceaglest 

**Can you quickly answer on this how actually network quality api is working.** 

@ceaglest your suggestions are good but its a business requirement as users has to muted themselves when they are listening to videos while chatting.

> When I looked at the Room SID, there was a long period (after everyone had joined) ...

First can you specify that long period in numbers.

> where some Participants had low estimated send bandwidth, 

How bandwidth is estimate to be low? What is the mechanism here?

>and also low network scores because of that. 

not understand here, what you mean.

> Getting to the root cause of why the available bandwidth is low, given the Participant's fast connections and proximity to us1 is something I might need help with from other team mates.

**Comment by jcaden** [comment]
Hi @smkrn110

I've been checking some of the participants in room RM0416cbf46f981f414f26b5c2a2e00676:

It looks like the congestion control algorithm is limiting the publication side to ~25-30 kbps for PAa87488dc4f80b440ef091bbdd10a49fb. This can be caused by both, network connectivity problems or also bad CPU performance in the client if it is overloaded. Basically, network quality detects that the available bandwidth has decreased under a limit and reduces network quality value.

Other participants like PAa87488dc4f80b440ef091bbdd10a49fb are having similar problems, but some others like PAf5c5b82ce784ca6441895a19357c06f8 have a better performance.
