### ISSUE TITLE
How to record and save videos on server?

### ISSUE THREAD

**Issue by iarmankhan** [twilio/twilio-video.js#664]
So, I've implemented twilio video chat in my website and it's working preety well.
Now I need to implement a feature like User can record his own video and then I will save it on server.
So my question is, Does twilio provide that kind of facility? and if yes then how can I implement this in node js or php?
Thanks.
Regards,
Arman Khan

**Comment by manjeshbhargav** [comment]
Hi @iarmankhan ,

I apologize for the delayed response. You can enable recording of all media in a Group or Small Group Room using our [Recordings and Compositions API](https://www.twilio.com/blog/2018/05/group-room-video-compositions-api.html).

If you want to record on the client side, the Video SDK does not have any support for that, but you should be able to achieve it in your application using the [MediaRecorder API](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder). Since MediaRecorder requires a MediaStream to record, you can build one for your local video and audio like this:

```js
const { createLocalTracks } = require('twilio-video');

createLocalTracks().then(tracks => {
  const mediaStream = new MediaStream(tracks.map(track => track.mediaStreamTrack));
  const mediaRecorder = new MediaRecorder(mediaStream);
  
  // Get the recorded data.
  mediaRecorder.ondataavailable = (e) => {
    // Upload to a server here.
  };

  // Start recording.
  mediaRecorder.start();

  // Stop recording.
  mediaRecorder.stop();
});
```

Let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by akshayKhot** [comment]
Hi @manjeshbhargav, I tried the above solution, but getting an error when starting a recording. Can you please have a look at #1116? Thanks!
