### ISSUE TITLE
beta5 questions 

### ISSUE THREAD

**Issue by theDude30** [twilio/twilio-video.js#74]
I need some help in knowing how to do certain things in the new twilio javascript beta5 version:
* How can i mute/unmute local media? 
I used to 
"localMedia = new Twilio.Video.LocalMedia();
localMedia.mute(true);"
* How can i switch between cameras in real-time? I used to pass constraints in "Video.getUserMedia(constraints)" , can i do "Twilio.Video.createLocalTracks(constraints)" instead ?

I need your help as i'm using the beta4 version and it has many bugs and issues.

**Comment by markandrus** [comment]
Hi @theDude30,

> * How can i mute/unmute local media?

In 1.0.0-beta5, instead of calling `mute` and `pause` on the LocalMedia object,  you call [`enable`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs/LocalTrack.html#enable__anchor) or [`disable`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs/LocalTrack.html#disable__anchor) on your LocalAudioTracks and LocalVideoTracks directly. So, for example, if you already have a reference to your LocalAudioTrack, you could call

```js
localAudioTrack.disable();
```

If you don't have a reference to any particular LocalAudioTrack, and just want to mute all of them currently shared by your LocalParticipant, you can do

```js
localParticipant.audioTracks.forEach(track => track.disable());
```

> * How can i switch between cameras in real-time?

Yes! You can definitely use [`createLocalTracks`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs/global.html#createLocalTracks__anchor), but we also have the more targeted functions [`createLocalAudioTrack`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs/global.html#createLocalAudioTrack__anchor) and [`createLocalVideoTrack`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs/global.html#createLocalVideoTrack__anchor).

For switching between cameras, you really have two options:

1. Remove the existing LocalVideoTrack, stop it, acquire a new LocalVideoTrack, and add it back.
2. Add both LocalVideoTracks, but just toggle their `enabled` state in order to "switch."

Here's the code for invoking `createLocalTracks`/`createLocalVideoTrack`. Which one you call depends on whether or not you might be requesting audio, too; whether or not you want to handle an Array of LocalTracks; etc.

```js
createLocalTracks({ audio: false, video: videoConstraints }).then(tracks => {
  console.log(tracks[0]);
  // => LocalVideoTrack
});
```

```js
createLocalVideoTrack(videoConstraints).then(track => {
  console.log(track);
  // => LocalVideoTrack
});
```

> I need your help as i'm using the beta4 version and it has many bugs and issues.

Please don't hesitate to share any bugs or improvements you identify in the new releases. Your feedback is valuable!

Best,
Mark

**Comment by markandrus** [comment]
Thanks for the report, @theDude30—this and #75 seem related. I think @manjeshbhargav's fix in https://github.com/twilio/twilio-video.js/commit/e20d86e217b445fbc2c95cb511a0a8289ffa14ee may fix this. We will test and ship the improvement in the next release.
