### ISSUE TITLE
[Q] Need to know about on going Twilio server changes?

### ISSUE THREAD

**Issue by smkrn110** [twilio/twilio-video.js#761]
@manjeshbhargav @philnash @syerrapragada and other team members.

Can you guys comment, since we often observed issues in our app that was working all fine and suddenly on the production side we start getting issues, is there a way we can track that you guys make some changes at the server application of Twilio, or pre-informed by you guys so we could re-test our application accordingly.

**Comment by philnash** [comment]
Hey! Before we dive into this on the Twilio side, can I ask what errors you are getting in your app and which version of `twilio-video` you are using? Thanks!

**Comment by smkrn110** [comment]
Hi, @philnash thanks for the response.

The issues are reported randomly by the end-user!

- that some of the user's streams get blurred, or webcam video (stops) 
- sometimes reported that network quality status API alerts for bad/very bad network still they having very high bandwidth internet and their webcams working fine too.

On the basis of that, I just get a 2nd thought that how server changes are being pushed by Twilio. What if the changes going on the server-side may have breaking changes.

**Comment by philnash** [comment]
Hi @smkrn110,

Ok, so this is not likely to be server side changes then, since you have no problems establishing a connection.

What I would recommend is that you instrument your front end so that you get more information from real use cases about errors within video calls. That way you will be able to look at the data and see what is affecting your calls and where the errors or drops are coming from. If you do see errors that are caused by the `twilio-video` library, I encourage you to report them then.

I'd also keep an eye on the `twilio-video` package and try to keep up to date (you can [subscribe to updates using tools like Libraries.io](https://libraries.io/npm/twilio-video)) as changes in APIs in the browsers could cause you issue and the Twilio Video team stay on top of those with the latest versions of the library.
