### ISSUE TITLE
Chrome 58: this._peerConnection.addStream is not a function

### ISSUE THREAD

**Issue by jskrzypek** [twilio/twilio-video.js#79]
I'm seeing this error when using 1.0.0-beta5 in our angular2 app:
```
TypeError: this._peerConnection.addStream is not a function
    at PeerConnectionV2.addMediaStream (twilio-video.js:4052)
    at PeerConnectionManager._getOrCreate (twilio-video.js:4309)
    at getConfigurationSucceeded (twilio-video.js:4338)
    at ZoneDelegate.1477.ZoneDelegate.invoke (zone.js:365)
    at Zone.1477.Zone.run (zone.js:125)
    at zone.js:760
    at ZoneDelegate.1477.ZoneDelegate.invokeTask (zone.js:398)
    at Zone.1477.Zone.runTask (zone.js:165)
    at drainMicroTaskQueue (zone.js:593)
    at WebSocket.ZoneTask.invoke (zone.js:464)
```
I can get past it by overriding the DefaultRTCPeerConnection for chrome by passing `options.RTCPeerConnection = RTCPeerConnection;`  into the `connect()` options. However, I don't see any tracks on the remote participants that connect in that scenario.

**Comment by jskrzypek** [comment]
If I use client with the workaround in chrome & one in firefox where I don't use the workaround, I can see the chrome participant's video & audio tracks just fine in the firefox client, but still see no tracks in the chrome client.

I suspect that if I were not using the workaround the streams might actually work, however when I leave it out I am not able to get past the error above when I try to connect, and nothing works.

**Comment by jskrzypek** [comment]
Oh i forgot to include, i was testing with Chrome 58. It could be a different version of Chrome will work

**Comment by jskrzypek** [comment]
I think this may be related to #77

**Comment by geoffreyabdallah** [comment]
@jskrzypek I've decided to hop over here because I think your issue (while producing similar results) is actually different than what is being experienced for the original poster of #77.

This is very strange, and I doubt it is a mac/windows thing but I'm on Mac. I've tested each combo of chrome/firefox connectivity and have not been able to replicate your issue within the node quickstart, and am testing on Chrome 58 now as well. I'll let Mark and the Twilio team issue weigh in on this since I'm at a loss!

**Comment by jskrzypek** [comment]
@geoffreyabdallah for what its worth this error occurs for me in the quickstart independent of connectivity, I see it when I try to connect to a room, regardless of if there's a participant there.

**Comment by markandrus** [comment]
Hi @jskrzypek,

I'm sorry you are having this issue—it is quite strange!

@geoffreyabdallah thanks for helping out. I agree with you, the issue @jskrzypek is having seems distinct from the issue in #77, so probably it is best we tackle it here. I've also attempted reproducing on a Mac with a fresh download of Chrome 58, and unfortunately I cannot reproduce. I also attempted to reproduce the issue inside of an Angular 2 app in case Zone.js was causing trouble (it has caused an issue in the past); however, no luck.

@jskrzypek would you mind please running the following—preferably within the context of the application—and sharing the results here? Also, can you clarify, do you see the issue both in Chrome 57 (stable) and 58 (beta)?

```js
console.log('UserAgent:', navigator.userAgent);
console.log('RTCPeerConnection:', RTCPeerConnection);
console.log('RTCPeerConnection.prototype.addStream', RTCPeerConnection.prototype.addStream);
```

For me, I receive the following:

```
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.54 Safari/537.36
RTCPeerConnection: function RTCPeerConnection() { [native code] }
RTCPeerConnection.prototype.addStream function addStream() { [native code] }
```

This indicates to me that nothing strange has overwritten the native RTCPeerConnection implementation. That's my current working theory... that something must be deleting or otherwise changing the `addStream` function.

> I can get past it by overriding the DefaultRTCPeerConnection for chrome by passing `options.RTCPeerConnection = RTCPeerConnection`;

Unfortunately I cannot really recommend this. Although we expose this feature for, e.g., our unit tests, the default "RTCPeerConnection" we load in Chrome is really a wrapper that works around some warts of the current RTCPeerConnection implementation in Chrome.

Could you please also try the following, just for a sanity check:

```
git clone https://github.com/twilio/twilio-video.js
cd twilio-video.js
git checkout 1.0.0-beta5
npm run install
npm run test:webrtc
```

This will run WebRTC tests (in both Chrome and Firefox) that basically verify our RTCPeerConnection wrappers are working as expected and that we have the necessary WebRTC-related functionality to support video. If there are any errors when you run this, that would be a big red flag. Could you please share the log output?

Also, if your system default is Chrome 57 (stable), the command above should be sufficient. Otherwise, you may need to set `CHROME_BIN` before running, e.g.

```
CHROME_BIN=path/to/chrome/beta npm run test:webrtc
```

Thanks!
Mark

**Comment by jskrzypek** [comment]
Well I feel kind of embarrassed now. I use uBlockOrigin as an ad blocker, but if course I have it whitelist localhost. Not long ago I also installed uBlockOrigin-Extra which blocks malicious websocket activity and then sorry if forgot about it. I had assumed it shared the whitelist with uBlockOrigin, since it uses uBlockOrigin to control some other settings, but apparently​ that's not the case. When I completely disabled the extension, the node quickstart worked for me. I'll close this issue now.

Thank you for your help, and I'm sorry for your wasted time and effort, @markandrus & @geoffreyabdallah. If it's any consolation I spent most of the week on this : disappointed:

**Comment by markandrus** [comment]
Hi @jskrzypek,

D'oh! That makes sense. Sorry you spent so much time on it, and sorry it took us a while to get to the bottom of it. FWIW, our team is still figuring out how best to triage issues on GitHub. There are definitely some betterments we could make, such as

* Documenting common issues that could lead to certain failures, especially as they relate to WebRTC (e.g., browser extensions, canary releases, etc.).
* Better explaining how to debug certain issues, how to capture debug logs (via the [`logLevel` parameter to `connect`](http://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs/global.html#ConnectOptions)), and when to provide them (e.g., by using GitHub [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)).

So I do think your ticket was useful, and hopefully it can guide us if anyone else hits a similar issue.

Thanks!
Mark
