### ISSUE TITLE
[Question] How to change/update the quality of video to be record.

### ISSUE THREAD

**Issue by kumail-raza** [twilio/twilio-video.js#853]
We observed that the video being recorded by Twilio is of very low quality and video recorded with the green shade. Is there a way to improvise it somehow, maybe by the quality of video being recorded is low, and some way to set the best quality?

Currently, I am not providing frameRate in constraint for Video, what is a default value, increasing framerate will help here?

**Comment by kumail-raza** [comment]
@manjeshbhargav @philnash ?

**Comment by manjeshbhargav** [comment]
@kumail-raza ,

Thanks for writing in with your question. I have forwarded your issue to the Media Recordings team. Someone should reach out to you with a clarification soon.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by spalmertwilio** [comment]
Good Afternoon @kumail-raza!

For anyone else reading this issue: a recording is a dump of the real-time media you are communicating in a Group Room. If you want to improve the recording quality, you must ensure that the communication quality is good. I'd recommend utilizing the [Network Quality API ](https://www.twilio.com/docs/video/using-network-quality-api) to monitor the quality of your communication.

If you are certain a Group Room had good communication quality but the recording is still degraded, or with a green hue, as in your case, please reply with the Room SID and, if possible, the Recording SID so that we may review.

Look forward to your reply.

Thanks,
Stephanie
