### ISSUE TITLE
Android 9 + Chrome Mobile View 69.0.34

### ISSUE THREAD

**Issue by pedronauck** [twilio/twilio-video.js#872]
Hi there,

I'm having trouble with `Android 7` and `Chrome 69.0.3497.100`, I'm trying to figure out what's happening but I think that is an incompatibility issue about the browser version and Twilio. 

That's the error:

<img width="723" alt="Screen Shot 2020-02-03 at 11 12 32 PM" src="https://user-images.githubusercontent.com/2029172/73710619-4b1e0300-46e3-11ea-888f-1a45b052cc09.png">

This is happening after I initiate the `new Device()` and get the `on:ready` callback as well.
Did you have any idea if there's something that I can do in order to fix this?

Thanks

**Comment by manjeshbhargav** [comment]
Hi @pedronauck ,

Thanks for writing in with your issue. We depend on the [HTMLMediaElement.setSinkId](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId) API to select the audio output device. If you look at the browser support table, Chrome on Android does not seem to have it. Unfortunately, I can't think of a workaround if the underlying Web API is not available.

Having said that, I don't think you need to programmatically select the audio output device on mobile, since the hardware should forward the audio samples to the newly connected device.

One more thing. It looks like you are using the Voice JS SDK. This is the repository for the Video JS SDK. In the future, please file issues related to the Voice JS SDK [here](https://github.com/twilio/twilio-client.js).

Thanks,

Manjesh Malavalli
JSDK Team
