### ISSUE TITLE
Remote tracks change dimensions throughout the call

### ISSUE THREAD

**Issue by eranp-medopad** [twilio/twilio-video.js#878]
We are having a group room with Web, iOS and Android . While the user is on the Web side using twilio js sdk, the dimensions of **the remote participant suddenly changes in the middle of the call**, 

We checked the websocket of VideoEvents and got this data changes throughout the call.
name: stat-report:
**1. dimensions: {width: 480, height: 640}
2. dimensions: {width: 360, height: 480}
3. dimensions: {width: 240, height: 320}**

As you can see dimensions are not constant. 

**1. Why it happens?
2. How can I keep the dimension locked down to the initial size of the remote participants?** 

 - Browser(s): Chrome
 - Operating System: windows 10 & mac os Catalina
 - twilio-video.js: 2.1.0
 - Third-party libraries (e.g., Angular, React, etc.): React

**Comment by manjeshbhargav** [comment]
Hi @eranp-medopad ,

VideoTrack dimensions change when the publisher's device changes its video capture/encoding resolutions based device CPU/networking resource availability. This is a good thing because otherwise it will be very difficult to maintain the video connection when you experience resource issues. There is now way to lock down the resolutions as of now.

Thanks,

Manjesh Malavalli
JSDK Team
