### ISSUE TITLE
Leaving up beta4

### ISSUE THREAD

**Issue by stueynet** [twilio/twilio-video.js#93]
We you be leaving up beta4 for a while? Once we were switched to 1.0.0 we got

```
Uncaught TypeError: M.LocalMedia is not a constructor
    at Object.<anonymous> (app-d0fad652b3fb7aa82741.js:34)
    at t (app-d0fad652b3fb7aa82741.js:1)
    at Object.<anonymous> (app-d0fad652b3fb7aa82741.js:34)
    at t (app-d0fad652b3fb7aa82741.js:1)
    at Object.<anonymous> (app-d0fad652b3fb7aa82741.js:34)
    at t (app-d0fad652b3fb7aa82741.js:1)
    at Object.<anonymous> (app-d0fad652b3fb7aa82741.js:28)
    at t (app-d0fad652b3fb7aa82741.js:1)
    at Object.<anonymous> (app-d0fad652b3fb7aa82741.js:34)
    at t (app-d0fad652b3fb7aa82741.js:1)
    at app-d0fad652b3fb7aa82741.js:1
    at app-d0fad652b3fb7aa82741.js:1
```

Need time to update our code.

**Comment by markandrus** [comment]
Hi @stueynet,

Sorry this affected your app. As I mentioned in my [previous comment](https://github.com/twilio/twilio-video.js/issues/82#issuecomment-294042259), we really shouldn't have pinned the `v1` URL to any particular beta release. So it was our mistake to set this URL in the first place :-(

Pre-releases like -beta4, -beta5, etc., don't make any guarantees about API compatibility. This is also why I suggested [pinning to the particular release URLs](https://github.com/twilio/twilio-video.js/issues/82#issuecomment-294043313), rather than the convenience URLs:

> You can get 1.0.0-beta5 from the following URLs:
>
> * https://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/docs
> * https://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/twilio-video.js
> * https://media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta5/twilio-video.min.js

(Note that, for any particular release, the artifacts will be accessible at similar URLs.)

Now that 1.0.0 is released, the `v1` URL is guaranteed to maintain API compatibility, as the subsequent releases will follow SemVer. However, I would recommend instead bundling the particular twilio-video.js release you plan to use in your `package.json` if at all possible (assuming your project uses Node).

Mark

**Comment by stueynet** [comment]
No totally get that. Not your fault. But I just wanted to confirm that the cdn link for beta4 will be up for a bit while we refactor.

**Comment by markandrus** [comment]
Yes, we will never delete it 👍 All `releases` URLs are immutable
