### ISSUE TITLE
LocalVideoTrack.isStarted() and .isStopped() are false of true simultaneously  

### ISSUE THREAD

**Issue by paulbrie** [twilio/twilio-video.js#940]
**Describe the bug**
LocalVideoTrack.isStarted() and .isStopped() are false of true simultaneously

**To Reproduce**
1. Go to: https://codesandbox.io/s/elastic-galois-tsspi?file=/pages/index.tsx
2. Hit the stop button
3. check the console

**Expected behavior**
I expect the localVideoTrack to be started or stopped, but not both 

**Environment (please complete the following information):**
 - OS: MacOS Catalina, 
 - Chrome 80.0.3987.163 (Build officiel) (64 bits)
 - SDK Version: 2.3.0

**Comment by manjeshbhargav** [comment]
Hi @paulbrie ,

Sorry for the delayed response. What you have shown is expected behavior. As soon as you created the LocalVideoTrack, it will take some time for the "started" event to fire, after which `isStarted` will be set to `true`. Once the LocalVideoTrack is stopped, the "stopped" event will fire and `isStopped` will be set to `true`. These two booleans are independent of each other, and indicate an event being raised. Hope this helps clear things up.

Thanks,

Manjesh Malavalli
JSDK Team
