### ISSUE TITLE
ICE connection state is "disconnected"

### ISSUE THREAD

**Issue by Awais-cb** [twilio/twilio-video.js#945]
stream does not work in the most cases

[PeerConnectionV2 #2: 680a99b6-ae2d-4884-9d8d-8660a166273c]: ICE connection state is "disconnected"

getting this in console with debug mode on using `logLevel: 'debug'`.any idea about this any help would be really appreciated

**Comment by makarandp0** [comment]
Hello @Awais-cb, Thank you for writing about this issue. 

Typically Ice connection state goes to disconnected  because of interruptions in network connectivity. We do have support for handling intermittent disconnections, and it should get back to connected state once network restores. 

Can you provide more details on the issue, Full log from the console and room-sid would definitely be useful. 

thanks,
Makarand

**Comment by Awais-cb** [comment]
HI @makarandp0 

Thanks for replying back 
my twilio room name = 273886-351949-15435

Here is the complete log file in this case i got connected to other user but after few seconds stream ended automatically.
[devs.oladoc.com-1586857423558.log](https://github.com/twilio/twilio-video.js/files/4474503/devs.oladoc.com-1586857423558.log)

**Comment by makarandp0** [comment]
@Awais-cb - Thanks fo the logs. I looked at records of your room (sid: RM9cbaa0b761806ca37636afbf91af05a4), and it does look like Chrome Mobile participant which was connected to signaling region in Germany encountered network issues, causing it to get disconnected.

**Comment by Awais-cb** [comment]
Thanks for check @makarandp0 is there any way we can reconnect all participants in case of connection failure?

**Comment by manjeshbhargav** [comment]
Hi @Awais-cb ,

Please refer to this [guide](https://www.twilio.com/docs/video/reconnection-states-and-events) for a way to detect whether you got disconnected from the Room due to network issues. Then, you can apply an exponential backoff waiting period before calling `connect()` again.

Thanks,

Manjesh Malavalli
JSDK Team
