### ISSUE TITLE
Traversal service STU/TURN not responding

### ISSUE THREAD

**Issue by athina635** [twilio/twilio-video.js#970]
I already use a free balance to test the transversal Network servers STUN/TURN and that works well after a day the server stop responding and we found that we have to upgrade the project and set some new balance we do that, we generate new tokens and the servers respond as well. the problem is after a day the server stops responding another time when we are using an upgrade project with 20$ balance on it.

we don't understand the problem. 

PS: we generate the token with our webRTC application with the Node.js server-side.

**Comment by anna-vasilko** [comment]
Hi @athina635 
I suspect that you hit the maintenance window on April 23d, which resulted in STUN/TURN returning HTTP 5xx errors when obtaining or validating TURN tokens during this operation.
Find details here https://status.twilio.com/incidents/ggrhzn9rv9kt

If so, it should not be happening anymore, please confirm!

**Comment by athina635** [comment]
Hello @anna-vasilko 
No, I guess now I'm using your servers by generating a token from node.js hen I do that after 24H the servers shut down and I have to regenerate manually new ones each time.

I really want to know if that is a problem and if I can make it an automatic process

Ps: I'm using my own webRTC application.

**Comment by anna-vasilko** [comment]
@athina635 Our STUN/TURN servers have been operational with no interruptions since April 23d. 
I suspect what happens is your access token gets expired therefore requests to our services get rejected as unauthorized. 

Twilio access tokens have a lifetime determined by your server when you generate the token, with a minimum of 3 minutes and a maximum of 24 hours. When an access token in your application expires, you must programmatically update the token to continue using Twilio's services.
More info:
https://www.twilio.com/docs/stun-turn/api?code-sample=code-create-token-resource-during-1-hour&code-language=PHP&code-sdk-version=6.x

**Comment by athina635** [comment]
@anna-vasilko Yes, that hat I found that the tokens will be expired by default in 24 hours. So I regenerate my token every 24 hours and that works fine. Thank you.

**Comment by anna-vasilko** [comment]
Glad to hear!
