### ISSUE TITLE
Participant disconnected because of duplicate identity

### ISSUE THREAD

**Issue by Awais-cb** [twilio/twilio-video.js#977]
is there any way to detect this 'Participant disconnected because of duplicate identity' in an event i currently want to show a message to the user that you switched the device.

Any help regarding this issue would be really appreciated and will help us improve our video calling experience over twilio.

**Comment by makarandp0** [comment]
Hello @Awais-cb , 

When a user gets disconnected - 'disconnect' event is emitted on the room. You can listen for  the [event](https://media.twiliocdn.com/sdk/js/video/releases/2.3.0/docs/Room.html#event:disconnected) and check the error parameter to see if the disconnect is because of duplicate identity.
something like
```
const room = await Video.connect(...);
room.on('disconnected', (room, error) => { 
  if (error.code === 53205) {
    // user logged on from another device
    alert(error.message);
  }
});
```

Let me know if that helps,
Thanks,
Makarand

**Comment by ehsanhosseini** [comment]
What I can do to avoid from happening this error again?

**Comment by makarandp0** [comment]
Hello @ehsanhosseini, This error indicates that another user joined with same `identity` as current user. The identity of the user is embedded in the token they use to join the room. Please see [documentation here](https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens) on how to generate tokens  Ensure that each unique user joins with unique identity. 

Thanks,
Makarand
