### ISSUE TITLE
Detecting when participants disconnect

### ISSUE THREAD

**Issue by tomas-c** [twilio/twilio-video.js#986]
The recommended approach ([ref](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices)) to signal when a participant leaves a room is to ensure that the following is run:

```
window.addEventListener('beforeunload', () => room.disconnect());
window.addEventListener('pagehide', () => room.disconnect());
```

This is not sufficient on Chrome on Android. 

 - [x] I have verified that the issue occurs with the latest twilio-video.js release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md).
 - [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-video.js/blob/master/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
 - [ ] I verified that the [Quickstart](https://github.com/twilio/video-quickstart-js) application works in my environment.
 - [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

**How to reproduce the issue:**

1. Start [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react)
2. Join a call from two devices, one of them from Chrome on Android
3. Close the call tab mid-call on the Android device
4. Observe the participant remains on the call for 45 seconds.

**Expected behavior:**

When a participant closes the call tab mid-call, the participant connection state should be marked as disconnected ASAP.

**Actual behavior:**

When a participant closes the call tab mid-call on Chrome on Android, it takes 15 seconds to enter reconnecting state and additional 45 seconds until the participant is removed. 

Other participants on the call can't tell if their peer permanently left the call or is just having connection troubles. This is what it looks like if you're the other participant (Laptop is online, Phone just closed the call tab):

![disconnect-ux](https://user-images.githubusercontent.com/5213953/80817815-0b739400-8bca-11ea-9fa7-461d560590d5.gif)

**Suggestion**

If there was a way to signal disconnection to Twilio via a HTTP request, the [Navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) could be used as a reliable way to send a request before a browser tab is closed.

**Software versions:**

 - [x] Browser(s): Chrome 81.0.4044.117
 - [x] Operating System: Android 10, Pixel XL
 - [x] twilio-video.js: 2.3.0
 - [x] Third-party libraries (e.g., Angular, React, etc.): [twilio-video-app-react](https://github.com/twilio/twilio-video-app-react) commit 1aa65abecbcf90a69bc3472b28edc277a8d95983

**Comment by makarandp0** [comment]
Thank you @tomas-c for reporting this issue and for the suggestion.
  
We do have an [http api](https://www.twilio.com/docs/video/api/participants?code-sample=code-remove-a-participant-3&code-language=curl&code-sdk-version=json) to kick participant off the room, that you can try from your unload handler with `navigator.sendBeacon`

One problem with the api though is that it requires `your_api_key_secret` which we do not recommend making part of your application.  I suggest you can add an endpoint in your server to mark user as disconnected that you can call from your app and then have your server call the twilio api.

BTW note that although the API accepts `ParticipantIdentityOrSid`. You would need to use sid since identity can be reused ( when the same participant connects from another device)  

Let me know if this helps. 
Thanks,
Makarand

**Comment by tomas-c** [comment]
Hey @makarandp0,

Looks like my suggestion will not work. Spent an evening on this and it could not find a way to reliably send a HTTP request on Chrome on Android when a tab is closed.

navigator.sendBeacon would be work on desktop but not on mobile, same with fetch() with keepAlive=true.

**Comment by PikaJoyce** [comment]
Hi @tomas-c, 

Unfortunately, these window events aren't always fired on mobile devices. This includes iOS as well as Android devices. I did some digging around for iOS specifically since there was a similar issue, and did some research for Android as well. 

I don't have a device on hand, but here's a few ideas for possible workarounds.

First, may be to check for both `onbeforeunload` as well as `onunload` since it seems that mobile isn't consistent with this event firing. There was a [chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=154321) filed but it doesn't seem like it'll be fixed.

Second suggestion would be to utilize the Page Visibility API. An example of that in use is found [here](https://www.twilio.com/docs/video/build-js-video-application-recommendations-and-best-practices#application-backgrounding-in-mobile-browsers). 

Please let me know if any of these workarounds are successful!

Thanks,
Joyce

**Comment by bryanhpchiang** [comment]
@tomas-c had a similar issue, i ended up connecting to a backend server with sockets (eg socketio), and then on disconnect i would manually disconnect users from the server side

**Comment by ardok** [comment]
Just something to add.

`pagevisibility` event does not fire on Chrome Custom Tab.
So, I have no idea how to detect that at the moment.

Posted the question on StackOverflow [here](https://stackoverflow.com/questions/66790832/is-there-any-javascript-event-that-is-fired-on-custom-tab-close).
